Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2019-10, with the labels that each got.

#47 Java version matching #35
  clients/cobol-lsp-vscode-extension/.vscodeignore
  clients/cobol-lsp-vscode-extension/jest.config.js
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/JavaVersionCheck.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/JavaVersionCheckTest.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
Labels: bug

#66 Release 0.8.3
  .gitignore
  CHANGELOG.md
  Jenkinsfile
  README.md
  clients/cobol-lsp-vscode-extension/.vscodeignore
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/jest.config.js
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/server/note.md
  clients/cobol-lsp-vscode-extension/src/JavaVersionCheck.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/JavaVersionCheckTest.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  com.ca.lsp.cobol/lsp-core-cobol-parser/pom.xml
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/resources/logback.xml
  com.ca.lsp.cobol/lsp-service-cobol/pom.xml
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/Highlights.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/references/References.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/resources/logback.xml
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/HighlightsTest.java
  com.ca.lsp.cobol/pom.xml
Labels: release

#68 Update CHANGELOG.md
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation
