Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2019-12, with the labels that each got.

#94 Convert copybook names to the upper case in order to make them case-insensitive #93
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserListenerImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestSameCopybooksWIthDifferentCases.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/UseCaseSuite.java
Labels: bug

#100 Update README.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: bug, documentation

#108 Make final field static too to fix technical debt
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/model/CopybookStorable.java
Labels: bug

#114 Remove unused imports and unnecessary comment
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/broadcom/lsp/cdi/LangServerCtx.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/PreprocessorCleanerService.java
Labels: code smell

#115 Make Analysis synchronized in order to avoid ConcurrentModificationException #79
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/validations/Analysis.java
Labels: improvement

#123 Engineering excellence
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/Communications.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/ServerCommunications.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
Labels: enhancement

#120 Add uncaught exception handling for async operations #78
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/Completions.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
Labels: enhancement
