Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-05, with the labels that each got.

#260 Add integration tests into Jenkins pipeline
  Jenkinsfile
  tests/theiaPrepare.sh
  tests/theia_automation_lsp/drivers/linux/.gitignore
  tests/theia_automation_lsp/robot_suites/lsp/local/chrome_lsp_local.robot
  tests/theia_automation_lsp/robot_suites/lsp/local/firefox_lsp_local.robot
  tests/zoweConfig/profiles/ssh/ssh_meta.yaml
  tests/zoweConfig/profiles/tso/tso_meta.yaml
  tests/zoweConfig/profiles/zosmf/zosmf_meta.yaml
Labels: pipeline

#332 ci: Fix Jenkins deploy stage
  Jenkinsfile
Labels: pipeline

#330 build: Change "-NEXT" suffix to "+NEXT"
  clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
Labels: pipeline

#334 Add java path to prerequisites in the readme file
  README.md
Labels: documentation

#328 fix: POC - Resolve local URI
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/LocalCopybookResolverTest.ts
  clients/cobol-lsp-vscode-extension/src/commands/ResolveLocalCopybooksCommand.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksPathGenerator.ts
  clients/cobol-lsp-vscode-extension/src/services/PathsService.ts
  clients/cobol-lsp-vscode-extension/src/services/settings/CopybookResolver.ts
  clients/cobol-lsp-vscode-extension/src/services/settings/LocalCopybookResolver.ts
  clients/cobol-lsp-vscode-extension/src/services/settings/util/SettingsUtils.ts
Labels: Rally, new feature

#353 Inform user about wrong credentials and stop sending other MF requests
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksDownloaderTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ZoweApiTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ZoweErrorTest.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksDownloader.ts
  clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts
  clients/cobol-lsp-vscode-extension/src/services/ZoweError.ts
Labels: new feature

#354 Fix webdriver log name for collection
  tests/reportCollection.sh
Labels: pipeline

#357 Added Jenkins params to run integration tests
  Jenkinsfile
Labels: pipeline

#331 fix: Create a .gitignore file if it doesn't exist #329
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/SettingsTest.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksDownloader.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksPathGenerator.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/AbstractCobolLinePreprocessorTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImplTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/dependency/CopybookDependencyServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/providers/SettingsProvider.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/FileSystemUtils.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/FileSystemConfiguration.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceE2ETest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/DependencyServiceTest.java
Labels: new feature
