Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-12, with the labels that each got.

#683 doc: Fix project path in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#681 Update client readme
  README.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation

#687 VariableUtils refactoring
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/VariableUtils.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/VariableUtilsTest.java
Labels: enhancement

#686 Explicitly specify the output directory for ANTLR
  server/pom.xml
Labels: enhancement

#688 Update the changelog for the release 0.16.1
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#691 MAPFAIL Produces a Semantic Error in HANDLE CONDITION
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsMapfail.java
Labels: bug

#696 build : specify the output dir for ANTLR
  server/pom.xml
Labels: pipeline

#700 Add buttons to client readme / add to compatibility section in readme
  README.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation

#699 VariableDefinitionDelegate refactoring
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
Labels: enhancement

#703 Remove prepopulating of settings.json with empty parameters for copybooks support
  clients/cobol-lsp-vscode-extension/src/__tests__/SettingsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
Labels: new feature

#705 feat: Add IDMS DML support for IDMS-CONTROL section #704
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsControlSectionAll.java
Labels: new feature

#707 Fix semantic analysis stop after XML query
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExtraLanguagesCleaned.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestTitleStatement.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestXmlQueryNotTerminatesSemanticAnalysis.java
Labels: bug
