Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-04, with the labels that each got.

#254 #251 - Fix nested copybook issue
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/dependency/CopybookDependencyService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/dependency/CopybookDependencyServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/FileSystemUtils.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/FileSystemConfiguration.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookSearchWithoutConfigTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceE2ETest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/DependencyServiceTest.java
Labels: bug, enhancement

#265 Patch Nested Copybooks
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/dependency/CopybookDependencyServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/FileSystemUtils.java
Labels: enhancement

#268 Fix multiple error messages while downloading copybooks
  clients/cobol-lsp-vscode-extension/src/CopybooksDownloader.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/DownloadQueueTest.ts
  clients/cobol-lsp-vscode-extension/src/services/DownloadQueue.ts
Labels: bug

#267 Calculate and return a full URI containing Zowe profile
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/.vscode/launch.json
  clients/cobol-lsp-vscode-extension/.vscode/tasks.json
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/src/__mocks__/vscode.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksDownloaderTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileServiceTest.ts
  clients/cobol-lsp-vscode-extension/src/commands/ChangeDefaultZoweProfile.ts
  clients/cobol-lsp-vscode-extension/src/commands/FetchCopybookCommand.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookFix.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksDownloader.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksPathGenerator.ts
  clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
  clients/cobol-lsp-vscode-extension/src/services/ProfileService.ts
  clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/model/ConfigurationSettingsStorable.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/dependency/CopybookDependencyServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/providers/SettingsProvider.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/FileSystemUtils.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/FileSystemConfiguration.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookSearchWithoutConfigTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceE2ETest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/DependencyServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/InitializeConfigurationTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/mocks/MockCopybookServiceImpl.java
Labels: Rally, enhancement

#271 TI release preparation
  README.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation

#274 Use shared volume to transfer package.
  Jenkinsfile
  tests/theiaPrepare.sh
  tests/theia_automation_lsp/robot_suites/lsp/local/firefox_lsp_local.robot
Labels: pipeline

#276 Release 0.11 changelog simplification
  README.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation, release

#219 Add semantic release tool integration.
  .gitattributes
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/.releaserc.yaml
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
Labels: TPSR, documentation, pipeline

#289 287 remove missing settings popup
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/TextDocumentSyncType.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookSearchWithoutConfigTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceE2ETest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
Labels: enhancement

#292 Update changelog
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#293 285 Nested copybooks failed to be retrieved at didOpen
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/src/services/CopybookFix.ts
  clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts
Labels: bug

#295 Change prepare.sh permission
  clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
Labels: pipeline

#297 Exclude release tool files from vsix package
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: pipeline

#298 "Change profile" in Quick fix menu when multiple profiles
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/.vscode/launch.json
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileServiceTest.ts
  clients/cobol-lsp-vscode-extension/src/commands/ChangeDefaultZoweProfile.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksCodeActionProvider.ts
  clients/cobol-lsp-vscode-extension/src/services/ProfileService.ts
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CpyRecognizedWithoutConfigTest.java
Labels: enhancement

#302 Special characters are causing grammatical errors
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolPreprocessor.g4
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestCpyNameWithSpecialChar.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/UseCaseSuite.java
Labels: bug

#305 "Profile not set" pop-up
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookFix.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksPathGenerator.ts
  clients/cobol-lsp-vscode-extension/src/services/ProfileService.ts
Labels: bug

#315 doc: Add committing requirements for contributors
  CONTRIBUTING.md
Labels: documentation

#314 Hide 'no errors found' message GH-312
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunications.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
Labels: enhancement

#311 Change log archive path pattern to relate on the user directory #307
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/resources/logback.xml
  com.ca.lsp.cobol/lsp-service-cobol/src/main/resources/logback.xml
Labels: bug

#319 doc: Fix changelog 0.11.1
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation
