Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-09, with the labels that each got.

#493 Allow Multi-line Errors Underscoring
  server/src/main/java/com/broadcom/lsp/domain/common/model/Position.java
  server/src/main/java/com/ca/lsp/cobol/service/delegates/validations/AnalysisResult.java
  server/src/main/java/com/ca/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
  server/src/main/java/com/ca/lsp/core/cobol/model/CopybookUsage.java
  server/src/main/java/com/ca/lsp/core/cobol/model/DocumentMapping.java
  server/src/main/java/com/ca/lsp/core/cobol/model/ExtendedDocument.java
  server/src/main/java/com/ca/lsp/core/cobol/model/Locality.java
  server/src/main/java/com/ca/lsp/core/cobol/model/SyntaxError.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImpl.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/transformer/ContinuationLineTransformation.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/impl/DocumentHierarchyLevel.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/impl/LocalityMappingUtils.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/impl/MultiMapSerializableHelper.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/CobolVariableContext.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/NamedSubContext.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/SemanticContext.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/SubContext.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/OutlineTreeBuilder.java
  server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  server/src/test/java/com/ca/lsp/cobol/service/delegates/completions/VariableCompletionTest.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookCaching.java
  server/src/test/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngineTest.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorImplTest.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImplTest.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/util/impl/LocalityMappingUtilsTest.java
  server/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableContextTest.java
  server/src/test/java/com/ca/lsp/core/cobol/visitor/VisitorSemanticAnalysisTest.java
Labels: bug, enhancement

#495 Fix a typo in DIVIDE-REMAINDER code snippets
  server/src/main/resources/com/ca/lsp/cobol/service/delegates/completions/LanguageSnippets.txt
Labels: bug

#500 ci: Change versioning pipeline
  .github/workflows/changelog.yml
  .github/workflows/release.yml
  Jenkinsfile
  clients/cobol-lsp-vscode-extension/server/note.md
  clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
  release/release-it-changelog.json
  release/release-it-release.json
  release/version-extract.js
  server/pom.xml
Labels: pipeline

#499 [doc] Copybooks section improvements
  README.md
  docs/images/CPYReplacing.gif
Labels: documentation

#503 ci: explicitly specify release-it version
  .github/workflows/changelog.yml
  .github/workflows/release.yml
Labels: dependencies, pipeline

#492 Provide default COBOL code snippets #484
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/snippets.json
Labels: new feature

#505 Fix checking program ID with quotes #477
  server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestProgramIdWithQuotes.java
Labels: bug

#510 Remove semantic release tool
  clients/cobol-lsp-vscode-extension/.releaserc.yaml
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
Labels: pipeline

#508 Fix incorrect indicator area error message #494
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/ProcessingConstants.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/CobolLineTypeEnum.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/CobolLineReader.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImpl.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestIndicatorAreaError.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImplTest.java
Labels: bug

#511 Fix Too Long Line Error Message
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImpl.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExtraSymbolsNotCauseErrorOnNextLine.java
Labels: enhancement

#514 Post-release merge
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: release

#516 refactor: Delete SneakyThrows
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/api/CopybookRepository.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/api/DataBusBroker.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/AbstractDataBusBroker.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRU.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/DefaultDataBusBroker.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/model/CopybookStorable.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/AnalysisFinishedEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/CopybookDepEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/FetchedCopybookEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/FetchedSettingsEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/RequiredCopybookEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/RunAnalysisEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/UnknownEventSubscriber.java
  server/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRUTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusGetFromCacheBadTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusGetFromCacheHappyTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusStoreHappyTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusSubscribeHappyTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusUnSubscribeTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DatabusBrokerTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DatabusEventSubscriptionE2ETest.java
Labels: enhancement

#517 refactor: rewrite CopybookRepository to use Guava cache
  server/src/main/java/com/broadcom/lsp/cdi/module/databus/DatabusModule.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/api/CopybookRepository.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/api/DataBusBroker.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRU.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/DefaultDataBusBroker.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/databus/model/CopybookStorable.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/SynchronousCopybookResolution.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/impl/MultiMapSerializableHelper.java
  server/src/test/java/com/broadcom/lsp/domain/CopybookStorableProvider.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRUTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookStorableTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusGetFromCacheBadTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusGetFromCacheHappyTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusStoreHappyTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusSubscribeBadTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusSubscribeHappyTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusUnSubscribeTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DatabusBrokerTest.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DatabusConfigProvider.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/event/CopybookEventsTest.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookCaching.java
Labels: enhancement

#522 Disable spellchecker for variables
  server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestSpellCheckNotAppliedForVariables.java
Labels: bug

#490 CICS language for COBOL - syntax analysis
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
  server/pom.xml
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CICSLexer.g4
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CICSParser.g4
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolLexer.g4
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolParser.g4
  server/src/main/resources/com/ca/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/ca/lsp/cobol/positive/ZipTextRegistry.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestErrorsInDifferentFiles.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsContainerStatementsArgumentsOrder.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsDatasetAllowedAsFileSynonym.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsFormatTimeStatementsArgumentsOrder.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsGetMainStatementArgumentsOrder.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsReadFileStatementPositive.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsSendStatementsArgumentsOrder.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsStartStatementArgumentsOrder.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExtraLanguagesCleaned.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExtraneousInputEOFExpecting.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestPerformWithoutEndNotCauseNPE.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestSetStatementParsedCorrectly.java
Labels: new feature

#523 (doc) clarify that local copybook folder paths need to be relative
  README.md
Labels: documentation

#524 (doc) Readme update for CICS support
  README.md
Labels: documentation

#525 Support COBOL paragraphs as CICS variables
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CICSParser.g4
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsSendStatementsArgumentsOrder.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExtraLanguagesCleaned.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestHandleConditionWorksWithParagraphs.java
Labels: new feature

#530 Make use case preprocessor compilable on build
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/UseCasePreprocessor.g4
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/UseCaseEngine.java
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessor.interp
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessor.tokens
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessorBaseListener.java
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessorLexer.interp
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessorLexer.java
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessorLexer.tokens
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessorListener.java
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessorParser.java
Labels: enhancement

#531 Exclude use case preprocessor generated files from JAR
  server/pom.xml
  server/src/test/antlr4/com/broadcom/usecase/UseCasePreprocessor.g4
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/UseCaseEngine.java
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: pipeline

#532 Lock copybook download queue in case of wrong MF credentials
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/DownloadQueueTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/MiddlewareTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/commands/FetchCopybookCommand.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookFix.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/DownloadQueue.ts
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/model/AnalysisFinishedEvent.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/model/RequiredCopybookEvent.java
  server/src/main/java/com/broadcom/lsp/domain/cobol/event/model/RunAnalysisEvent.java
  server/src/main/java/com/ca/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/com/ca/lsp/cobol/service/CopybookProcessingMode.java
  server/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  server/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  server/src/main/java/com/ca/lsp/cobol/service/TextDocumentSyncType.java
  server/src/main/java/com/ca/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/main/java/com/ca/lsp/cobol/service/utils/SettingsParametersEnum.java
  server/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/CobolPreprocessor.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/impl/CobolPreprocessorImpl.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/CopybookResolution.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/GrammarPreprocessor.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/GrammarPreprocessorListenerFactory.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorImpl.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/SynchronousCopybookResolution.java
  server/src/test/java/com/broadcom/lsp/domain/cobol/event/CopybookEventsTest.java
  server/src/test/java/com/ca/lsp/cobol/service/CopybookProcessingModeTest.java
  server/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
  server/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookCaching.java
  server/src/test/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngineTest.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorImplTest.java
Labels: new feature

#535 Show missing copybooks status only on demand
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/DownloadQueueTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/DownloadQueue.ts
Labels: new feature

#538 doc: Add changelog for 0.15
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#537 fix: Fix downloading many copybooks while typing
  server/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
Labels: bug
