Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-11, with the labels that each got.

#591 Remove deprecated COMMUNICATION SECTION support
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/outline/OutlineNodeNames.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
Labels: bug

#602 Test/improve code coverage for UI
  clients/cobol-lsp-vscode-extension/jest.config.js
  clients/cobol-lsp-vscode-extension/sonar-project.properties
  clients/cobol-lsp-vscode-extension/src/__tests__/ChangeDefaultZoweProfileTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/EditDatasetPathsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/OpenSettingsCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/fetchCopybookCommandTest.spec.ts
Labels: enhancement

#607 Fix exception on not formatted line
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/CobolLineIndicatorProcessorImpl.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/impl/CobolLineIndicatorProcessorImplTest.java
Labels: bug

#609 Interrupt Analysis on Closing Request
  server/src/main/java/com/broadcom/lsp/cobol/core/annotation/CheckThreadInterruption.java
  server/src/main/java/com/broadcom/lsp/cobol/core/annotation/HandleThreadInterruption.java
  server/src/main/java/com/broadcom/lsp/cobol/core/annotation/ThreadInterruptAspect.java
  server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
  server/src/test/java/com/broadcom/lsp/cobol/core/annotation/HandleThreadInterruptionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
Labels: new feature

#608 Add Language Features Support for Sections #502
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/GroupContext.java
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/SemanticContext.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/CompletionOrder.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/SectionCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SectionLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/AnalysisResult.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/test/antlr4/com/broadcom/usecase/UseCasePreprocessor.g4
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
  server/src/test/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/semantics/GroupContextTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/CompletionsChainTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/ConstantCompletionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/SectionCompletionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/SnippetCompletionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/SectionLocationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCompilerDirectivesNotCauseErrors.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestErrorsInDifferentFiles.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsGetMainStatementArgumentsOrder.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestMisspelledKeywordWarningInCorrectPosition.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphNotDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSectionDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSyntaxErrorTraversedThroughHierarchy.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/TestData.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCaseEngine.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: new feature

#618 Make parsing interruptible
  server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/InterruptingTreeListener.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
  server/src/test/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngineTest.java
Labels: enhancement

#625 Remove deprecated sections support
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
Labels: bug, enhancement

#632 Add missing RES compiler options
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestNoErrorsOnRes.java
Labels: bug

#629 fix: Fix exception logging after analysis #546
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
Labels: bug

#628 fix: Copybook with Name in Quotes Not Recognized #620
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolDocumentModel.java
  server/src/test/antlr4/com/broadcom/usecase/UseCasePreprocessor.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCopybookNameWithQuotes.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: bug

#633 fix: Allow CICS to be a variable name #597
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCICSVariableNameAllowed.java
Labels: bug

#635 Fix syntax error on ERASE in CICS SEND
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsSendStatementsArgumentsOrder.java
Labels: bug

#639 refactor : remove unused class found in coverity scan
  server/src/main/java/com/broadcom/lsp/cobol/core/strategy/Messages.java
Labels: enhancement

#634 Fix syntax error on VALUE 77
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestValue77Allowed.java
Labels: bug

#636 feat : New didChange Request Should Interrupt Previous Analysis #616
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
Labels: new feature

#622 using custom thread pool executor #615
  server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/databus/impl/AbstractDataBusBroker.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/databus/impl/DefaultDataBusBroker.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/DatabusModule.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunications.java
  server/src/main/java/com/broadcom/lsp/cobol/service/utils/CustomThreadPoolExecutor.java
  server/src/main/java/com/broadcom/lsp/cobol/service/utils/CustomThreadPoolExecutorService.java
  server/src/test/java/com/broadcom/lsp/cobol/LangServerBootstrapTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusSubscribeBadTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusSubscribeHappyTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusUnSubscribeTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusBrokerTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusConfigProvider.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestResponsesNotContainLineBreaks.java
  server/src/test/java/com/broadcom/lsp/cobol/utils/CustomThreadPoolExecutorTest.java
Labels: enhancement

#637 refactor : get rid of LangServerCtx
  server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/MisspelledKeywordDistance.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/LangServerCtx.java
  server/src/test/java/com/broadcom/lsp/cobol/ConfigurableTest.java
  server/src/test/java/com/broadcom/lsp/cobol/LangServerBootstrapTest.java
  server/src/test/java/com/broadcom/lsp/cobol/negative/NegativeTest.java
  server/src/test/java/com/broadcom/lsp/cobol/positive/FolderTextRegistry.java
  server/src/test/java/com/broadcom/lsp/cobol/positive/PositiveTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CompletionResolutionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/HighlightsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/CompletionsChainTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/DocumentOccurrencesTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestFormatTrim.java
Labels: enhancement

#640 fix: TITLE Statement Not Allowed Before ID DIVISION #595
  .gitignore
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExtraneousInputEOFExpecting.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestTitleStatement.java
Labels: bug

#642 Remove unused LD rule
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
Labels: enhancement

#641 Fix syntax error on SKIP directives
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSkipStatementsAllowedEverywhere.java
Labels: bug

#613 Support Termination Requests #590
  clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
  server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
  server/src/main/java/com/broadcom/lsp/cobol/core/annotation/CheckServerShutdownState.java
  server/src/main/java/com/broadcom/lsp/cobol/core/annotation/DisposableService.java
  server/src/main/java/com/broadcom/lsp/cobol/core/annotation/HandleShutdownState.java
  server/src/main/java/com/broadcom/lsp/cobol/core/annotation/NonSyntheticMethodMatcher.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolLanguageServer.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/DisposableLanguageServer.java
  server/src/test/java/com/broadcom/lsp/cobol/ConfigurableTest.java
  server/src/test/java/com/broadcom/lsp/cobol/LangServerBootstrapTest.java
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
  server/src/test/java/com/broadcom/lsp/cobol/core/annotation/HandleShutdownStateTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/annotation/NonSyntheticMethodMatcherTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolLanguageServerTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/DocumentExtensionTests.java
  server/src/test/java/com/broadcom/lsp/cobol/service/mocks/TestLanguageServer.java
Labels: new feature

#648 refactor: Resolve Coverity Issues
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/outline/OutlineTreeBuilder.java
  server/src/main/java/com/broadcom/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
Labels: enhancement

#658 fix : YYMMDD in CICS FORMATTIME Produces Errors #647
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsFormatTimeStatementsArgumentsOrder.java
Labels: bug

#659 fix : COUNT As A Variable Name Produces Syntax Error #646
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCOUNTVariableNameAllowed.java
Labels: bug

#656 Fix exposing semantic errors to document
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingForSeveralTokensInOneLine.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSemanticErrorsFromCopybooksShownInDocument.java
Labels: bug

#655 Make copybook coloring work without analysis
  clients/cobol-lsp-vscode-extension/package.json
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/Communications.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunications.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
Labels: new feature

#661 fix : Complete outline Request for Unsupported Files #653
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
Labels: bug

#662 fix : Support "Varying" in FILE-CONTROL #623
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVaryingSupportForFileAssignment.java
Labels: bug

#660 fix : Fix PIC Clause with period produces Syntax Errors in Some Cases #593
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestPICVariableStructure.java
Labels: bug

#664 fix : Check PROGRAM-ID is Case In-Sensitive #594
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestProgramNameIsCaseInsensitive.java
Labels: bug

#663 fix : Support COBOL CICS intersected keyword in Program ID #600
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestKeywordInProgramId.java
Labels: bug

#666 Troubleshooting and Subroutine Support sections added
  README.md
Labels: documentation

#665 fix : Support variable Usages Separated by Commas without Whitespaces…
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVariableUsageSeparatedByComma.java
Labels: bug

#669 ci: Build release package with correct telemetry key
  .github/workflows/release.yml
  release/release-it-release.json
Labels: pipeline

#671 refactor: Remove deprecated test utils
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/validations/UseCaseUtils.java
Labels: enhancement

#672 refactor: Remove unused event classes
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/api/CopybookEventFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/factory/CopybookDepSubscriberFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/factory/FetchedSettingsSubscriberFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/impl/CopybookDepEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/impl/FetchedSettingsEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/model/CopybookDepEvent.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/model/DataEventType.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/model/FetchedSettingsEvent.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusEventSubscriptionE2ETest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusTestConstants.java
Labels: enhancement

#674 Allow FILLER for level 77 definition
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVariableDefinitionsAllowFILLER.java
Labels: bug

#675 Fix analysis stop on a client exception
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CopybookServiceTest.java
Labels: bug

#676 Provide changelog for release 0.16.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#677 Explicitly use 'this' in DownloadQueue.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/DownloadQueue.ts
Labels: enhancement

#682 HANDLE AID CLEAR() Produces a Syntax Error in EXEC CICS
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsHandleAidClear.java
Labels: bug
