Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-08, with the labels that each got.

#447 Fix version updating CI script
  clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
Labels: pipeline

#448 Disable copybook analysis for extended documents #441
  clients/cobol-lsp-vscode-extension/package-lock.json
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/CobolPreprocessor.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/impl/CobolPreprocessorImpl.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/AnalyseCopybookTask.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/AnalyseCopybookTaskFactory.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/CopybookAnalysis.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/CopybookParallelAnalysis.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/CobolSemanticParser.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserImpl.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserListenerImpl.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolCleanExtraLanguageTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableCheckTest.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/model/RequiredCopybookEvent.java
  com.ca.lsp.cobol/lsp-core-domain/src/test/java/com/broadcom/lsp/domain/cobol/event/CopybookEventsTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookProcessingMode.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/TextDocumentSyncType.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/validations/LanguageEngineFacade.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/WorkspaceFileService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookProcessingModeTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/DocumentExtensionTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/validations/UseCaseUtils.java
Labels: documentation, new feature

#451 Updates to readme and changelog before release
  CHANGELOG.md
  README.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation

#453 docs: Add NOTICE file
  NOTICE.md
Labels: documentation

#452 fix: disable copybook analysis only on extended document
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserListenerImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookProcessingMode.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookProcessingModeTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/DocumentExtensionTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
Labels: bug

#454 build: update Zowe Imperative version
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: dependencies

#455 Update LICENSE
  LICENSE
Labels: documentation

#460 build: Set fixed versions for semantic-release libs
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: dependencies, pipeline

#462 docs: Update release date in the change logs
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: release

#471 Fix syntax analysis termination with unexpected copy statements #464
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolLexer.g4
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolParser.g4
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestExtraneousInputEOFExpecting.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMissingCopybookAtBeginningNotBreaksSyntaxAnalysis.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
Labels: bug

#439 feat: Outline view support
  server/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
  server/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  server/src/main/java/com/ca/lsp/cobol/service/delegates/validations/AnalysisResult.java
  server/src/main/java/com/ca/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/CobolVariableContext.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/SemanticContext.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/NodeType.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/OutlineNodeNames.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/OutlineTreeBuilder.java
  server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/RangeUtils.java
  server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  server/src/test/java/com/ca/lsp/cobol/service/DocumentExtensionTests.java
  server/src/test/java/com/ca/lsp/cobol/service/MyLanguageServerImplTest.java
  server/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
  server/src/test/java/com/ca/lsp/cobol/service/delegates/completions/CopybookCompletionTest.java
  server/src/test/java/com/ca/lsp/cobol/service/delegates/completions/ParagraphCompletionTest.java
  server/src/test/java/com/ca/lsp/cobol/service/delegates/completions/VariableCompletionTest.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestOutlineTree.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestOutlineTreeLineNumbers.java
  server/src/test/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngineTest.java
  server/src/test/java/com/ca/lsp/core/cobol/semantics/outline/RangeUtilsTest.java
  server/src/test/java/com/ca/lsp/core/cobol/visitor/VisitorSemanticAnalysisTest.java
Labels: new feature

#483 docs: Adjust the error message for 80 chars limit
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImpl.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExtraSymbolsNotCauseErrorOnNextLine.java
Labels: documentation, enhancement

#485 Underscore the Copy Statement if the Copybook Contains a Syntax Error
  server/src/main/java/com/broadcom/lsp/domain/common/model/Position.java
  server/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
  server/src/main/java/com/ca/lsp/core/cobol/model/CopybookUsage.java
  server/src/main/java/com/ca/lsp/core/cobol/model/ExtendedDocument.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImpl.java
  server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/transformer/ContinuationLineTransformation.java
  server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookCaching.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookWithIndirectRecursiveDependencyIsDetected.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestErrorsInDifferentFiles.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestIdentificationDivisionInCopybookWithError.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestMissingNestedCopybookProducesError.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestSyntaxErrorTraversedThroughHierarchy.java
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessor.interp
  server/src/test/java/com/ca/lsp/cobol/usecases/engine/parser/TestPreprocessorParser.java
  server/src/test/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngineTest.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorImplTest.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/GrammarPreprocessorListenerImplTest.java
  server/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/util/impl/PositionMappingUtilsTest.java
  server/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableContextTest.java
  server/src/test/java/com/ca/lsp/core/cobol/visitor/VisitorSemanticAnalysisTest.java
  server/src/test/resources/TestPreprocessor.g4
Labels: new feature
