Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-07, with the labels that each got.

#410 Fix sending download requests for nested copybooks
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/model/AnalysisFinishedEvent.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
Labels: bug

#409 Updates to Readme and Changelog for version 0.12.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation

#412 build: Remove unused dependency
  com.ca.lsp.cobol/pom.xml
Labels: dependencies

#418 ci: Disable changelog updating on release
  clients/cobol-lsp-vscode-extension/.releaserc.yaml
  clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
Labels: release

#422 Java 11 migration
  Jenkinsfile
  clients/cobol-lsp-vscode-extension/src/__tests__/JavaCheckTest.ts
  clients/cobol-lsp-vscode-extension/src/services/JavaCheck.ts
  com.ca.lsp.cobol/lsp-core-cobol-parser/pom.xml
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/CopybookParallelAnalysis.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CompilerDirectivesTransformation.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/CobolLineUtils.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/semantics/CobolVariableContext.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImplTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/line/rewriter/impl/CobolCommentEntriesMarkerImplTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/line/rewriter/impl/CobolLineIndicatorProcessorImplTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolCleanExtraLanguageTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableCheckTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableContextTest.java
  com.ca.lsp.cobol/lsp-core-domain/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRUTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/LangServerBootstrap.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CompletionResolutionTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MultiDocumentDefinitionTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/WatcherServiceImplTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/WorkspaceServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/actions/FindCopybookCommandTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/references/DocumentOccurrencesTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookWithIndirectRecursiveDependencyIsDetected.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestFormatTrim.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/utils/KeywordsTest.java
  com.ca.lsp.cobol/pom.xml
Labels: enhancement

#428 Reorganize Maven Structure
  com.ca.lsp.cobol/lsp-core-cobol-parser/pom.xml
  com.ca.lsp.cobol/lsp-core-domain/pom.xml
  com.ca.lsp.cobol/lsp-service-cobol/pom.xml
  com.ca.lsp.cobol/pom.xml
Labels: enhancement

#425 Improvment of performance by resolving ambiguities
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolParser.g4
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolPreprocessor.g4
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
Labels: enhancement

#423 Syntax coloring support
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: new feature

#436 [Doc] Update Bitlang dependency in readme
  README.md
Labels: documentation

#438 [Doc] add mention of go to definition on copybook names feature
  README.md
Labels: documentation

#437 Add support for Area A&B
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/CobolTestSuite.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/visitor/VisitorSemanticAnalysisTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMarginAB.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/UseCaseSuite.java
Labels: new feature

#434 Dispose diagnostic messages when user close the document #385
  clients/cobol-lsp-vscode-extension/.vscode/settings.json
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
Labels: bug

#440 Add margin A check for FD and SD level indicators
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMarginAB.java
Labels: enhancement
