Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-10, with the labels that each got.

#542 Introduce index variable definition support
  server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsContainerStatementsArgumentsOrder.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestIncorrectTableCallUnderlined.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestIndexDefinition.java
Labels: bug, new feature

#551 Typed variable model + split definition logic
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CICSParser.g4
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolLexer.g4
  server/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolParser.g4
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/ConditionalDataName.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/ElementItem.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/GroupItem.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/IndependentDataItem.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/IndexItem.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/RenameItem.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/StructuredVariable.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/TableDataName.java
  server/src/main/java/com/ca/lsp/core/cobol/model/variables/Variable.java
  server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestLevel77Definition.java
  server/src/test/java/com/ca/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
Labels: enhancement

#552 Publish FE tests in Sonar Cloud
  .gitignore
  Jenkinsfile
  README.md
  clients/cobol-lsp-vscode-extension/.vscodeignore
  clients/cobol-lsp-vscode-extension/jest.config.js
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/sonar-project.properties
  sonar-project.properties
Labels: pipeline

#555 DI for preprocessor
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderDelegate.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CompilerDirectivesTransformation.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
  server/src/test/java/com/broadcom/lsp/cobol/core/AbstractCobolLinePreprocessorTest.java
Labels: documentation, enhancement

#558 exclude generated scannerwork folders from vsix
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: pipeline

#557 Implementation for folder-based positive tests registry
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
  server/src/test/java/com/broadcom/lsp/cobol/positive/FolderTextRegistry.java
  server/src/test/java/com/broadcom/lsp/cobol/positive/PositiveTest.java
  server/src/test/java/com/broadcom/lsp/cobol/positive/ZipTextRegistry.java
Labels: enhancement

#559 Ignore non-release-spec folders
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: pipeline

#561 refactor: Fix coverity security alerts
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/DatabusModule.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/DefaultModule.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/LangServerCtx.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
Labels: code smell

#563 Exclude Junit 4 dependencies
  server/pom.xml
  server/src/test/java/com/broadcom/lsp/cobol/core/semantics/outline/RangeUtilsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CopybookProcessingModeTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCopybookCaching.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestMarginAB.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestOutlineTree.java
Labels: dependencies

#562 refactor: refactor Databus copybook caching
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/resolution/CopybookResolution.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/resolution/CopybookResolutionProvider.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/resolution/SynchronousCopybookResolution.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/databus/api/CopybookRepository.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/databus/api/DataBusBroker.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/databus/impl/AbstractDataBusBroker.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/databus/impl/CopybookRepositoryLRU.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/databus/impl/DefaultDataBusBroker.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/api/CopybookEventFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/factory/FetchedCopybookSubscriberFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/factory/RequiredCopybookSubscriberFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/impl/FetchedCopybookEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/impl/RequiredCopybookEventSubscriber.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/model/DataEventType.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/model/FetchedCopybookEvent.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/model/RequiredCopybookEvent.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/CopybookRepositoryLRUTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusGetFromCacheBadTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusGetFromCacheHappyTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusStoreHappyTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusSubscribeBadTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusSubscribeHappyTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusUnSubscribeTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusBrokerTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusConfigProvider.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusEventSubscriptionE2ETest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusTestConstants.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/event/CopybookEventSubscribersTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/event/CopybookEventsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CopybookServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/WorkspaceServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/DocumentOccurrencesTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/validations/UseCaseUtils.java
  server/src/test/java/com/broadcom/lsp/cobol/service/mocks/MockCopybookService.java
  server/src/test/java/com/broadcom/lsp/cobol/service/mocks/MockCopybookServiceImpl.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCopybookCaching.java
Labels: enhancement

#564 build: Include node_modules into VSIX package
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: dependencies

#567 Move unsupported files notification into problems console #173
  server/pom.xml
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunications.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
Labels: TPSR, enhancement

#570 code refactoring with lombok annotations
  server/src/main/java/com/broadcom/lsp/cobol/core/model/Locality.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/ElementItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/strategy/Messages.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/impl/CobolLineIndicatorProcessorImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusBrokerTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusConfigProvider.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusEventSubscriptionE2ETest.java
Labels: enhancement

#571 Add an unwrap method to ResultWithErrors
  server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/ResultWithErrors.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
Labels: enhancement

#574 Positive tests fix
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
  server/src/test/java/com/broadcom/lsp/cobol/positive/FolderTextRegistry.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/validations/UseCaseUtils.java
Labels: bug

#575 replace dormant javax Nonnull with Lombok NonNull
  server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
  server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/ResultWithErrors.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/GroupItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/RenameItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/TableDataName.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessor.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReader.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderDelegate.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CompilerDirectivesTransformation.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/CobolCommentEntriesMarkerImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/CobolInlineCommentEntriesNormalizerImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/CobolLineUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/DocumentHierarchyLevel.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/LocalityMappingUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/PreprocessorStringUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/ReplacingService.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/ReplacingServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolLanguageServer.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/SettingsServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/WatcherService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/WatcherServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/actions/CodeActionProvider.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/actions/FindCopybookCommand.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/Completion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/Completions.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/ConstantCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/CopybookCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/KeywordCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/ParagraphCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/SnippetCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/VariableCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/formations/TrimFormation.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/ConstantLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/CopybookLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/Occurrences.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/ParagraphLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SemanticElementOccurrences.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SemanticLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/VariableLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/providers/ClientProvider.java
  server/src/main/java/com/broadcom/lsp/cobol/service/utils/FileSystemService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/utils/WorkspaceFileService.java
  server/src/test/java/com/broadcom/lsp/cobol/core/AbstractCobolLinePreprocessorTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/impl/CobolLineReaderImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CompletionResolutionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/SnippetCompletionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: dependencies, enhancement

#576 test: Increase CopybookServiceTests
  server/src/test/java/com/broadcom/lsp/cobol/service/CopybookServiceTest.java
Labels: enhancement

#573 Enhancement/externalize error messages properties
  server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/com/broadcom/lsp/cobol/core/messages/LocaleEnum.java
  server/src/main/java/com/broadcom/lsp/cobol/core/messages/LocaleStore.java
  server/src/main/java/com/broadcom/lsp/cobol/core/messages/LocaleStoreImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/messages/MessageService.java
  server/src/main/java/com/broadcom/lsp/cobol/core/messages/PropertiesMessageService.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/transformer/ContinuationLineTransformation.java
  server/src/main/java/com/broadcom/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolLanguageServer.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/Communications.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunications.java
  server/src/main/java/com/broadcom/lsp/cobol/service/utils/SettingsParametersEnum.java
  server/src/main/resources/com/broadcom/lsp/cobol/core/strategy/Messages.txt
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
  server/src/test/java/com/broadcom/lsp/cobol/core/AbstractCobolLinePreprocessorTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/messages/LocaleStoreImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/messages/PropertiesMessageServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/transformer/ContinuationLineTransformationTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/strategy/CobolErrorStrategyTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/visitor/VisitorSemanticAnalysisTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolLanguageServerTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/DocumentExtensionTests.java
  server/src/test/java/com/broadcom/lsp/cobol/service/WorkspaceServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/validations/UseCaseUtils.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestResponsesNotContainLineBreaks.java
  server/src/test/resources/message/messages_fr.properties
  server/src/test/resources/resourceBundles/Test_messageServiceEmptyFile_en.properties
  server/src/test/resources/resourceBundles/messages_en.properties
  server/src/test/resources/resourceBundles/test-2_en.properties
  server/src/test/resources/resourceBundles/test_en.properties
  server/src/test/resources/resourceBundles/test_fr.properties
Labels: enhancement, new feature

#577 Clarify settings description
  clients/cobol-lsp-vscode-extension/package.json
Labels: documentation

#579 improvement: Improve Semantic Analysis for Paragraphs #526
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestMarginAB.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphNotDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphSectionDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVaryingCorrect.java
  server/src/test/resources/message/messages_fr.properties
  server/src/test/resources/resourceBundles/messages_en.properties
Labels: new feature

#583 fix: variable usage works in a call statement
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCallVariableUsages.java
Labels: bug

#580 Set log level run time
  clients/cobol-lsp-vscode-extension/package.json
  server/src/main/java/com/broadcom/lsp/cobol/core/messages/LogLevelUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolLanguageServer.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/utils/SettingsParametersEnum.java
  server/src/test/java/com/broadcom/lsp/cobol/core/messages/LogLevelUtilsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolLanguageServerTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/WorkspaceServiceTest.java
Labels: new feature

#587 add new code snippets exec-sql-include and exec-cics
  clients/cobol-lsp-vscode-extension/snippets.json
Labels: new feature

#586 Support INCLUDE in EXEC SQL to build extended document #480
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSqlIncludeStatement.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSqlIncludeStatementNotDefinedCorrectly.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSqlIncludeStatementNotFoundCopybook.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSqlIncludeStatementUsingRepeatedly.java
Labels: new feature
