Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-03, with the labels that each got.

#182 Zowe copybook tracker #208
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/README.md
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/CopybooksDownloader.ts
  clients/cobol-lsp-vscode-extension/src/CopybooksDownloaderCodeActionProvider.ts
  clients/cobol-lsp-vscode-extension/src/DownloadQueue.ts
  clients/cobol-lsp-vscode-extension/src/PathUtils.ts
  clients/cobol-lsp-vscode-extension/src/ProfileService.ts
  clients/cobol-lsp-vscode-extension/src/ZoweApi.ts
  clients/cobol-lsp-vscode-extension/src/__mocks__/vscode.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksDownloaderTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/DownloadQueueTest.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/tslint.json
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/FileSystemServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/actions/FindCopybookCommand.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/FileSystemConfiguration.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/TestModule.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyLanguageServerImplTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/WorkspaceServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/actions/FindCopybookCommandTest.java
Labels: enhancement, new feature

#222 Setup Jest to collect coverage
  .gitignore
  clients/cobol-lsp-vscode-extension/.vscodeignore
  clients/cobol-lsp-vscode-extension/jest.config.js
Labels: enhancement

#223 Introduce bindings for language engine module #24
  com.ca.lsp.cobol/lsp-core-cobol-parser/pom.xml
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/broadcom/lsp/cdi/EngineModule.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/impl/CobolPreprocessorImpl.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/cleaner/impl/CobolDocumentCommentingCleanerListener.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/AnalyseCopybookTask.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/AnalyseCopybookTaskFactory.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/CopybookParallelAnalysis.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolReplacementMapping.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserImpl.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserListenerImpl.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/PreprocessorStringUtils.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/impl/PreprocessorCleanerServiceImpl.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/CobolTestSuite.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngineTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/util/PreprocessorStringUtilsTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolCleanExtraLanguageTest.java
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableCheckTest.java
  com.ca.lsp.cobol/lsp-service-cobol/pom.xml
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/broadcom/lsp/cdi/module/service/ServiceModule.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/LangServerBootstrap.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/ConfigurableTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/positive/PositiveTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/validations/UseCaseUtils.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/mocks/MockWorkspaceService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/AnalyzeCopybookCaching.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/NegativeUseCase.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/PositiveUseCase.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookWithIndirectRecursiveDependencyIsDetected.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestCopybookWithRecursiveDependencyIsDetected.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMissingCopybookNotInVariableList.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMissingCopybooksReturnsError.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestResponsesNotContainLineBreaks.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestSameCopybooksWIthDifferentCases.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestVariableStructureInCopybooksWithMissingLevels.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestVariableStructureIsBuiltWithCopybooks.java
  com.ca.lsp.cobol/pom.xml
Labels: enhancement

#221 187 consume settings in Copybook Service
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  com.ca.lsp.cobol/lsp-core-cobol-parser/pom.xml
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/api/CopybookEventFactory.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/factory/FetchedSettingsSubscriberFactory.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/FetchedSettingsEventSubscriber.java
  com.ca.lsp.cobol/lsp-core-domain/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DatabusEventSubscriptionE2ETest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/broadcom/lsp/cdi/module/service/ServiceModule.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/model/ConfigurationSettingsStorable.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/FileSystemServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/Communications.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/CopybookMessageInfo.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunications.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/dependency/CopybookDependencyService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/dependency/CopybookDependencyServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/providers/SettingsProvider.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/FileSystemUtils.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/SettingsParametersEnum.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/FileSystemConfiguration.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/TestModule.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/positive/PositiveTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookSearchWithoutConfigTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceE2ETest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/DependencyServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/FileSystemServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/InitializeConfigurationTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyLanguageServerImplTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/mocks/MockFileSystemService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/AnalyzeCopybookCaching.java
Labels: enhancement, new feature

#224 Remove file not used
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/FileSystemServiceImpl.java
Labels: code smell

#227 Finalize LRU algorithm #226
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  com.ca.lsp.cobol/lsp-core-domain/pom.xml
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRU.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/databus/model/CopybookStorable.java
  com.ca.lsp.cobol/lsp-core-domain/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRUTest.java
Labels: Rally, enhancement

#96 Test automation Integration with Eclipse pipeline #95
  tests/theia_automation_lsp/.gitignore
  tests/theia_automation_lsp/README.md
  tests/theia_automation_lsp/drivers/__init__.py
  tests/theia_automation_lsp/drivers/drv_config.py
  tests/theia_automation_lsp/inc/__init__.py
  tests/theia_automation_lsp/inc/cfg/__init__.py
  tests/theia_automation_lsp/inc/cfg/env_constants.py
  tests/theia_automation_lsp/inc/conditions/__init__.py
  tests/theia_automation_lsp/inc/conditions/attr_has_value.py
  tests/theia_automation_lsp/inc/conditions/element_with_locator_nomore_exist.py
  tests/theia_automation_lsp/inc/decorators/__init__.py
  tests/theia_automation_lsp/inc/decorators/wait_till_exist.py
  tests/theia_automation_lsp/inc/exceptions/__init__.py
  tests/theia_automation_lsp/inc/exceptions/assert_exception.py
  tests/theia_automation_lsp/inc/exceptions/custom_timeout_exception.py
  tests/theia_automation_lsp/inc/exceptions/element_not_found_exception.py
  tests/theia_automation_lsp/inc/exceptions/general_exception.py
  tests/theia_automation_lsp/inc/exceptions/no_line_number_exception.py
  tests/theia_automation_lsp/inc/exceptions/unexpected_notification_message_exception.py
  tests/theia_automation_lsp/inc/exceptions/unknown_locator_exception.py
  tests/theia_automation_lsp/inc/helpers.py
  tests/theia_automation_lsp/inc/theia/__init__.py
  tests/theia_automation_lsp/inc/theia/config.py
  tests/theia_automation_lsp/inc/theia/constants.py
  tests/theia_automation_lsp/inc/theia/lsp_constants.py
  tests/theia_automation_lsp/inc/theia/ui.py
  tests/theia_automation_lsp/inc/theia/zos_constants.py
  tests/theia_automation_lsp/keywords/__init__.py
  tests/theia_automation_lsp/keywords/general.py
  tests/theia_automation_lsp/keywords/monako.robot
  tests/theia_automation_lsp/keywords/monako_editor_wrappers.py
  tests/theia_automation_lsp/lib/__init__.py
  tests/theia_automation_lsp/lib/common_driver.py
  tests/theia_automation_lsp/lib/common_engine.py
  tests/theia_automation_lsp/lib/file_explorer.py
  tests/theia_automation_lsp/lib/monako_editor.py
  tests/theia_automation_lsp/lib/zos_chrome_engine.py
  tests/theia_automation_lsp/lib/zos_firefox_engine.py
  tests/theia_automation_lsp/requirements.txt
  tests/theia_automation_lsp/robot_suites/__init__.robot
  tests/theia_automation_lsp/robot_suites/lsp/__init__.robot
  tests/theia_automation_lsp/robot_suites/lsp/local/__init__.robot
  tests/theia_automation_lsp/robot_suites/lsp/local/chrome_lsp_local.robot
  tests/theia_automation_lsp/robot_suites/lsp/local/firefox_lsp_local.robot
  tests/theia_automation_lsp/test_files/cobol/USER1.cbl
  tests/theia_automation_lsp/test_files/cobol/USER2.cbl
Labels: TPSR, documentation, enhancement

#234 Remove copybooks Quick Fix on the server side due to it is a client responsibility
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/broadcom/lsp/cdi/module/service/ServiceModule.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/actions/FindCopybookCommand.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/TestModule.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/WorkspaceServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/actions/FindCopybookCommandTest.java
Labels: enhancement

#231 Address Stack Overflow error on pipeline
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  com.ca.lsp.cobol/lsp-core-domain/pom.xml
  com.ca.lsp.cobol/lsp-service-cobol/pom.xml
  com.ca.lsp.cobol/pom.xml
Labels: bug, pipeline

#238 Truncate copybook names #175
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/src/services/DependencyService.ts
Labels: bug

#244 PDS and PDSE 8 character informational message
  com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserListenerImpl.java
Labels: new feature
