Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2020-06, with the labels that each got.

#381 test: Improve code coverage for JavaCheck
  clients/cobol-lsp-vscode-extension/jest.config.js
  clients/cobol-lsp-vscode-extension/src/__tests__/JavaCheckTest.ts
  clients/cobol-lsp-vscode-extension/src/services/JavaCheck.ts
Labels: enhancement

#359 Clarify copybook retrieval setup procedure
  README.md
Labels: documentation

#344 [Doc] Improve the readme introduction
  README.md
Labels: documentation

#379 test: Add ZoweApi unit tests for client
  clients/cobol-lsp-vscode-extension/src/__tests__/ZoweApiTest.ts
Labels: enhancement

#383 [Doc] Updates for local copybook support
  README.md
  docs/images/CPYGoToDefinition.gif
Labels: documentation

#377 Update tests/theia_automation_lsp/README.md file
  tests/theia_automation_lsp/README.md
Labels: documentation

#382 Client code coverage
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.ts
  clients/cobol-lsp-vscode-extension/src/commands/FetchCopybookCommand.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookFix.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookURI.ts
Labels: enhancement

#389 IntegrationTests: Fix warnings and change tags
  Jenkinsfile
  tests/theiaPrepare.sh
  tests/theia_automation_lsp/robot_suites/lsp/local/firefox_lsp_local.robot
Labels: enhancement, pipeline

#392 Adjust the info message about missing copybooks #391
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookFix.ts
Labels: new feature

#398 refactor: Delete unused plugin properties #23
  clients/cobol-lsp-vscode-extension/package.json
Labels: enhancement

#397 Avoid many error messages for copybook downloading
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/MiddlewareTest.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookURI.ts
  clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/api/CopybookEventFactory.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/factory/AnalysisFinishedSubscriberFactory.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/AnalysisFinishedEventSubscriber.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/model/AnalysisFinishedEvent.java
  com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/model/DataEventType.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/SettingsService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/SettingsServiceImpl.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/SettingsParametersEnum.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/validations/UseCaseUtils.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/mocks/MockCopybookService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/mocks/MockCopybookServiceImpl.java
Labels: Rally, bug, new feature

#396 Fix: unexpected Java 8 expected error message #333
  clients/cobol-lsp-vscode-extension/src/__tests__/JavaCheckTest.ts
  clients/cobol-lsp-vscode-extension/src/services/JavaCheck.ts
Labels: bug

#394 fix: representation of setting.json in Theia #393
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/LocalCopybookResolverTest.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
Labels: bug

#399 384 Simplify UI for copybook management
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileServiceTest.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookURI.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybooksCodeActionProvider.ts
  clients/cobol-lsp-vscode-extension/src/services/ProfileService.ts
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/actions/FindCopybookCommand.java
  com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/actions/FindCopybookCommandTest.java
Labels: enhancement

#400 Avoid many error messages for copybook downloading
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/MiddlewareTest.ts
  clients/cobol-lsp-vscode-extension/src/commands/FetchCopybookCommand.ts
  clients/cobol-lsp-vscode-extension/src/services/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
Labels: enhancement

#402 refactor: Remove popup message for GIT unsupported operation #318
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/Communications.java
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunications.java
Labels: bug

#403 Change settings paths on the server side #393
  com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/SettingsParametersEnum.java
Labels: bug

#406 test: Fix types of asserted events
  com.ca.lsp.cobol/lsp-core-domain/src/test/java/com/broadcom/lsp/domain/cobol/event/CopybookEventSubscribersTest.java
Labels: code smell

#407 Doc: Add compatibility section to readme
  README.md
Labels: documentation
