Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-05, with the labels that each got.

#905 ci: fix maven build
  Jenkinsfile
Labels: pipeline

#907 feat: Tune TAB functionality #906
  clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
Labels: new feature

#917 Fix incorrect descriptions for some tokens
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/SnippetCompletion.java
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageSnippets.txt
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/completions/SnippetCompletionTest.java
Labels: bug

#903 Idms on
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDelete.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsAcceptDbStatements.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsConDisconnectStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsFindObtainStatements.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReturnStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsSetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsTransferStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsWriteClause.java
Labels: new feature

#913 feat: Determine Effective Types for Variables #882
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/EffectiveDataType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/GroupItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/MultiTableDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/TableDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/UsageClause.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/UsageFormatUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryNodeTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIncompatiblePicAndUsageClause.java
Labels: new feature

#920 Fix Coverity issues
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetToBooleanStatement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetToOnOffStatement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetUpDownByStatement.java
Labels: enhancement

#912 refactor: public api doesn't depend on didOpen/Change
  clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
  server/src/main/java/org/eclipse/lsp/cobol/domain/event/model/AnalysisResultEvent.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
Labels: enhancement

#919 Separate DB2 SQL grammar
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CommonCobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/TechnicalLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/MessageServiceParser.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/Timing.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/EmbeddedCode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/EmbeddedCodeNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/NodeType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/DocumentHierarchyLevel.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityMappingUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/SemanticContext.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/Db2SqlVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/ParserListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/main/resources/org/eclipse/lsp/cobol/core/strategy/SpecialTokenHandling.properties
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/impl/LocalityMappingUtilsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/visitor/VisitorSemanticAnalysisTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestControlCompilerDirective.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestErrorOnReadyTraceOutsideProcedureDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIndicatorAreaError.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestPseudoTextContentConstraint.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestRemarksAreUnsupported.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestRemarksSectionIsUnsupported.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlIncludeStatementNotDefinedCorrectly.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlStatementMustCodedInAreaB.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTyposOnCompilerDirectives.java
Labels: enhancement

#923 Datacom support part1
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/ImplicitFields.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlIncludeStatementForDefinedFields.java
Labels: enhancement, new feature

#924 test: Add Allure Report
  tests/.gitignore
  tests/README.md
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/index.ts
  tests/package.json
  tests/yarn.lock
Labels: UI tests, enhancement

#927 Fix working with URIs provided by E4E #922
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/ProfileService.ts
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/FileSystemService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileServiceTest.java
Labels: bug

#930 build: upgrade client dependencies
  clients/cobol-lsp-vscode-extension/jest.config.js
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/SettingsTest.spec.ts
Labels: dependencies
