Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-07, with the labels that each got.

#996 refactor: Cancel name length check for COPY IDMS
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsCopy.java
Labels: bug

#997 Show condition names in variable description
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/NodeConverter.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/DocumentationUtils.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java
Labels: new feature

#999 test: Return back cypress tags functionality
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/package.json
  tests/yarn.lock
Labels: UI tests

#1000 Allow semicolons as statement terminators
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/TechnicalLexer.g4
  server/src/test/antlr4/org/eclipse/usecase/UseCasePreprocessor.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSemicolonNotAllowedInIdentificationDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSemicolonNotAllowedOnNotTerminatingPositions.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestStatementTerminationWithSemicolons.java
Labels: bug

#995 IDMS Variables Support
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableUsageNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/Db2SqlVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtilTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsAcceptDbStatements.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsBindStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsConDisconnectStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsCopy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsEraseStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsFindObtainStatements.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsGetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsIfStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsInquireMapStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsKeepStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapInStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapOutInStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapOutStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsModifyMapStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsModifyStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyAfterIfNotProducesError.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReturnStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsSections.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsStartpageStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsStoreStatement.java
Labels: new feature

#1001 Allow COPY MAID clauses with qualifiers
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifier.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifierMissingCopybook.java
Labels: enhancement

#1002 Fix Black Duck issues
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: dependencies

#1003 Fix test that fails after merging
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestStatementTerminationWithSemicolons.java
Labels: enhancement

#1006 build: Fix stack trace in Theia
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: dependencies

#1007 test: Add new test cases
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
Labels: UI tests

#1008 choir: Update coloring for COPY MAID
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
Labels: enhancement

#1016 Create changelog for 0.20.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#1018 Update README with IDMS copybook sentence
  README.md
Labels: documentation

#1015 Add padding for 88 level variables hover
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ConditionDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ValueInterval.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/NodeConverter.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/DocumentationUtils.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtilTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/Test88ThruHover.java
Labels: enhancement

#1024 fix: Maintain string length while replacing #974
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/ReplacingServiceImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookReplacePatterns.java
Labels: bug

#1030 Fix code duplication
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataName.java
Labels: code smell

#1031 Update changelog for 0.20.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#1033 After release 0.20.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: release

#1036 Fix server freeze on typos in MAP SECTION
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapSectionDoesntProduceNPE.java
Labels: bug

#1049 ci: add UI tests
  Jenkinsfile
  tests/.gitignore
  tests/cypress.json
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F96125.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/index.ts
  tests/package.json
  tests/test_files/project/settings/basic.json
  tests/tsconfig.json
  tests/yarn.lock
Labels: UI tests, pipeline
