Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-03, with the labels that each got.

#781 Describe new local copybook features in readme
  README.md
Labels: documentation

#791 Add general Theia configs method
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F95834.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F96125.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/test_files/project/settings/basic.json
  tests/test_files/project/settings/empty.json
  tests/test_files/project/settings/subroutines.json
  tests/test_files/project/settings/testing.json
Labels: UI tests, enhancement

#786 feature: US729486 Extend LSP API #785
  server/src/main/java/org/eclipse/lsp/cobol/domain/event/model/AnalysisResultEvent.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/ExtendedApiService.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
Labels: new feature

#797 test: Remove broadcom naming from configurations
  tests/.gitignore
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/package.json
  tests/test_files/project/settings/basic.json
  tests/test_files/project/settings/empty.json
  tests/test_files/project/settings/subroutines.json
  tests/test_files/project/settings/testing.json
  tests/yarn.lock
Labels: UI tests

#799 feat: add cobol world pattern to IDE editor
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/syntaxes/lang-config.json
Labels: new feature

#800 extract cics lexer grammar #264
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CommonCobolLexer.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
Labels: enhancement

#790 feat: Add IDMS DML support for DB statements part 1 #704
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyIdms.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsBindStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsConDisconnectStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsControlSectionAll.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsCopy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsEraseStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsFindObtainStatements.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsGetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsKeepStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsModifyStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsRollbackStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsSections.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsStoreStatement.java
Labels: new feature

#804 fix: coloring for divisions
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: bug

#802 refactor: fix potential null dereference
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/outline/OutlineTreeBuilder.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
Labels: enhancement

#803 feature: US729482 Create COBOL LS VSC extension public API #801
  clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
Labels: new feature

#793 feat: variables hovering
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/AbstractVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ElementItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/IndependentDataItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/IndexItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MnemonicName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MultiTableDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/StructuredVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/TableDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/Variable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/SemanticContext.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/outline/RangeUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
  server/src/main/java/org/eclipse/lsp/cobol/domain/modules/ServiceModule.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/VariableCompletion.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/hover/HoverProvider.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHover.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/references/ElementOccurrences.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/AnalysisResult.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/test/java/org/eclipse/lsp/cobol/TestModule.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/VariableUsageUtilsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/ElementItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/GroupItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/IndependentDataItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/IndexItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/MnemonicNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/MultiTableDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/TableDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/references/ElementOccurrencesTest.java
Labels: new feature

#805 test: Add tagging to Cypress tests
  tests/.gitignore
  tests/README.md
  tests/cypress.json
  tests/cypress/integration/LSP/F101836.spec.js
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F95834.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F96125.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/plugins/index.js
  tests/package.json
  tests/tag_statistics.sh
  tests/test_files/project/settings/subroutines.json
  tests/test_files/project/testing/MORECOOL.CPY
  tests/yarn.lock
Labels: UI tests

#807 Use Che-Theia compatible Nodejs (v. 10.5-11.15) methods
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
Labels: enhancement

#806 test: add TC319689(hovering) test
  tests/cypress/integration/LSP/lsp.spec.js
  tests/test_files/project/HOVER.CBL
Labels: UI tests

#808 fix: Add color to hover message
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHover.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java
Labels: bug

#811 fix: fix misspelled Keyword Warning Shown on a Correct Token #760
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/KeywordSuggestions.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/MisspelledKeywordDistance.java
  server/src/main/resources/org/eclipse/lsp/cobol/core/visitor/Keywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSectionRange.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlKeywordAllowedAsCobolVarIdentifier.java
Labels: bug

#812 chore: update coloring schema
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement

#783 feat: Support the compiler directive statements
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CommonCobolLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/messages/PropertiesMessageService.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/ProcessingConstants.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerFactory.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderDelegate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/CompilerDirectives.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/CompilerDirectivesTransformation.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/transformer/ContinuationLineTransformation.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityMappingUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/ReplacingService.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/ReplacingServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/SearchPattern.java
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/core/AbstractCobolLinePreprocessorTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/MessageServiceParserTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/messages/PropertiesMessageServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/impl/GrammarPreprocessorImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/impl/ReplacingServiceImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategyTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCompilerDirectivesNotCauseErrors.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestControlCompilerDirective.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookReplacePatterns.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCpyNameWithSpecialChar.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDelete.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEnd.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndpage.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEnterCompilerDirective.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestFunctionalIdentifiersAllowedInCopyReplace.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestMissingNestedCopybookProducesError.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNestedCopyReplaceClause.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestPicClausesNotCauseSyntaxErrors.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestPseudoTextContentConstraint.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplacingAppliedOneByOne.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplacingByEmptyPseudoText.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplacingNotAppliedRecursively.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplacingPseudoTextReplacesLevelNumber.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTitleStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: new feature

#818 test: Add TC319969 test case
  tests/cypress/integration/LSP/lsp.spec.js
Labels: UI tests

#820 Make common grammar for Processor and Cobol #710
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CommonCobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
Labels: enhancement

#822 feat: Support REPLACE compiler directive statements #116
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerFactory.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/PreprocessorStack.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/ReplacePreProcessorListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/PreprocessorStringUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/ReplacingServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/TokenUtils.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/impl/GrammarPreprocessorImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplaceCompilerDirective.java
Labels: new feature

#824 fix: Make extended API call result serializable #823
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/ExtendedApiResult.java
  server/src/main/java/org/eclipse/lsp/cobol/service/ExtendedApiService.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
Labels: bug

#825 refactor: change java unit tests to use only one thread
  server/src/test/java/org/eclipse/lsp/cobol/domain/databus/impl/DefaultDataBusBrokerTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
  server/src/test/java/org/eclipse/lsp/cobol/service/utils/TestThreadPoolExecutor.java
  server/src/test/java/org/eclipse/lsp/cobol/service/utils/TestThreadPoolExecutorTest.java
Labels: enhancement

#826 fix: wrong variable definition caused by REPLACE compiler directive s…
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/ReplacePreProcessorListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/PreprocessorStringUtils.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplaceCompilerDirective.java
Labels: bug

#827 test: Add Zowe test suite
  tests/.gitignore
  tests/README.md
  tests/cypress/integration/LSP/zowe.spec.js
  tests/cypress/support/index.ts
  tests/test_files/project/settings/clist_local.json
  tests/test_files/project/settings/clist_nopass.json
  tests/test_files/project/settings/clist_wrongpass.json
  tests/test_files/zowe/profiles/zosmf/local.yaml
  tests/test_files/zowe/profiles/zosmf/noPass.yaml
  tests/test_files/zowe/profiles/zosmf/wrongPass.yaml
  tests/yarn.lock
Labels: UI tests

#830 fix: two COPY REPLACE statements work wrong
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplacingSameCopybookTwice.java
Labels: bug

#831 fix: correct variable definition error processing for multy context case
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/SyntaxTreeEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/AntlrVariableDefinitionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/Node.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/NodeType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RootNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/SectionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/VariableDefinitionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/VariableUsageNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/NodeTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/visitor/VisitorSemanticAnalysisTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestProgramContexts.java
Labels: bug

#829 Fix error position for compiler directives
  server/src/main/java/org/eclipse/lsp/cobol/core/model/CobolLine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/CobolLineTypeEnum.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderDelegate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/CompilerDirectivesTransformation.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/rewriter/CobolLineIndicatorProcessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/writer/CobolLineWriterImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/domain/modules/EngineModule.java
  server/src/test/java/org/eclipse/lsp/cobol/core/AbstractCobolLinePreprocessorTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/reader/impl/CobolLineReaderImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/writer/impl/CobolLineWriterImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCompilerDirectivesPositive.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNoErrorOnCompilerDirectives.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTyposOnCompilerDirectives.java
Labels: bug

#833 feat: Allow analysis regardless file extension
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/Communications.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/DocumentExtensionTests.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
Labels: new feature

#838 test: fix tests
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/integration/LSP/zowe.spec.js
Labels: UI tests

#840 ci: Add maven integraion
  Jenkinsfile
Labels: pipeline

#787 style: Allow having any year in the copyright header
  server/src/style/checkstyle.xml
  server/src/style/javaHeader.txt
Labels: pipeline

#834 perf: fix typo check performance
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/KeywordSuggestions.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/MisspelledKeywordDistance.java
Labels: enhancement

#835 style: make readable name for positive tests
  server/src/test/java/org/eclipse/lsp/cobol/positive/CobolText.java
Labels: enhancement

#843 ci: Trim Jenkins pod label
  Jenkinsfile
Labels: pipeline
