Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-11, with the labels that each got.

#1176 ci: Update Jenkinsfile for cypress container
  Jenkinsfile
Labels: pipeline

#1178 ci: downgrade vsce version
  Jenkinsfile
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: pipeline

#1175 test: Use predefined selectors
  Jenkinsfile
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F95834.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/integration/LSP/zowe.spec.js
  tests/yarn.lock
Labels: enhancement, UI tests

#1182 Remove memory leak in AST
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/IfNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
Labels: enhancement

#1184 refactor: Clean up CobolVisitor
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
Labels: code smell

#1185 refactor: Add hooks for external grammar nodes
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/org/eclipse/lsp/cobol/core/strategy/SpecialTokenHandling.properties
Labels: enhancement

#1135 feat: Add grammar for DaCo R/W transaction statement #1126
  clients/cobol-lsp-vscode-extension/snippets.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/MessageServiceParser.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFReadTransaction.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFWriteTransaction.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFWriteTransactionLengthDoesNotProduceNPE.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFWriteTransactionToDoesNotProduceNPE.java
Labels: new feature, hacktoberfest-accepted
