Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-09, with the labels that each got.

#1069 Improve tests
  server/src/test/java/org/eclipse/lsp/cobol/ConfigurableTest.java
  server/src/test/java/org/eclipse/lsp/cobol/positive/CobolText.java
  server/src/test/java/org/eclipse/lsp/cobol/positive/FileBasedTest.java
  server/src/test/java/org/eclipse/lsp/cobol/positive/PerformanceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/positive/PositiveTest.java
  server/src/test/java/org/eclipse/lsp/cobol/positive/TypingTest.java
Labels: enhancement

#1084 Fix exception on an incomplete 88 definition
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIncomplete88DoesNotProduceNPE.java
Labels: bug

#1089 doc: Update Slack link in README.md
  README.md
Labels: documentation

#1088 Fix exception on incomplete EXEC statement
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTypingExecDoesNotProduceException.java
Labels: bug

#1086 Fix an exception on EXEC variable name
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecVarDoesNotProduceNPE.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTypingExecDoesNotProduceException.java
Labels: bug

#1090 Fix exception on END token
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfDoesNotProduceError.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableEndDoesNotProduceNPE.java
Labels: bug

#1091 Fix exception on empty USAGE clause
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNoExceptionOnEmptyUsage.java
Labels: bug

#1092 fix: Fix throwing an exception on half typed variable definition
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java
Labels: bug

#1096 fix: Fix exception on incomplete SET UP statement
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetDownByDoesNotProduceExceptions.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDoesNotProduceExceptions.java
Labels: bug

#1097 fix: Fix throwing an exception on half typed DECLARATIVES Section
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDeclarativesSection.java
Labels: bug

#1098 Fix exception on incomplete OCCURS TO clause
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestOccursToDoesNotProduceExceptions.java
Labels: bug

#1100 show unknown variable definition error
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestUnknownVariableDefinition.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: enhancement

#1099 doc: Update license file for the grammar
  LICENSE.md
Labels: documentation

#1101 add COBOL preprocessor keywords in Coloring schema
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement

#1102 Update changelog for the release 0.21.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation

#1104 Fix UI tests
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
Labels: UI tests

#1105 Update package.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: documentation

#1110 After release 0.21.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: release

#1103 feat: Add IDMS snippets #704
  clients/cobol-lsp-vscode-extension/snippets.json
Labels: new feature

#1111 refactor node processing way
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/CodeBlockUsageNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/Node.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ParagraphsNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProcedureDivisionBodyNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramEndNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramIdNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/SectionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/FileDescriptionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/GroupItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/StandAloneDataItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableUsageNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableWithLevelNode.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/NodeProcessingTest.java
Labels: enhancement

#1112 rename VariableWithLevelNode::processNode to not confuse programmers
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableWithLevelNode.java
Labels: code smell

#1116 Remove identifier tokens from error messages
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/IdentifierReplacing.java
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/SpecialTokenReplacing.java
  server/src/main/resources/org/eclipse/lsp/cobol/core/strategy/SpecialTokenHandling.properties
  server/src/test/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategyTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestAsteriskBeforeCopyDoesntBreakAnalysis.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestErrorOnReadyTraceOutsideProcedureDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecVarDoesNotProduceNPE.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNoNullPointerExpForIncompleteReplaceStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestRemarksAreUnsupported.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTitleStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestUnexpectedTextInIdentificationDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableEndDoesNotProduceNPE.java
Labels: bug, enhancement

#1118 Extend the list of predefined copybooks
  server/src/main/java/org/eclipse/lsp/cobol/core/model/CopybookModel.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookConfig.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/SettingsService.java
  server/src/main/resources/implicitCopybooks/DFHEIBLK.cpy
  server/src/test/java/org/eclipse/lsp/cobol/service/CopybookServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/validations/UseCaseUtils.java
Labels: enhancement

#1119 Make typing test parallel
  server/src/test/java/org/eclipse/lsp/cobol/positive/FileBasedTest.java
  server/src/test/java/org/eclipse/lsp/cobol/positive/TypingTest.java
Labels: enhancement

#1123 Fix server freeze on EXEC statement
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityMappingUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecCicsDoesNotFreezeAnalysis.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecSqlDoesNotFreezeAnalysis.java
Labels: bug

#1124 Refactor validation of subschema name
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/MessageServiceParser.java
Labels: enhancement

#1127 Fix exception on typing EXEC SQL
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNoStringIndexOutOfBoundsOnExecSql.java
Labels: bug

#1131 test: bump semver-regex in /tests
  tests/yarn.lock
Labels: dependencies, UI tests, javascript
