Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-08, with the labels that each got.

#1051 ci: remove deploy stage
  Jenkinsfile
Labels: pipeline

#1050 test: exclude failing UI test
  tests/cypress/integration/LSP/F96125.spec.js
Labels: UI tests

#1053 doc: Add extension to the license file
  LICENSE.md
Labels: documentation

#1056 test: Add TC328483
  tests/cypress/integration/LSP/lsp.spec.js
Labels: UI tests

#1063 Fix consuming extra tokens by statements
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestObtainAnyAfterMoveParsedCorrectly.java
Labels: bug

#1065 refactor: don't show comments on hover on FD/SD variables.
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/TechnicalLexer.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestFileDescriptor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsCopy.java
Labels: bug

#1066 Fix incorrect error on EXEC CICS
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityFindingUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityMappingUtils.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityFindingUtilsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestAsteriskBeforeCopyDoesntBreakAnalysis.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestControlCompilerDirective.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEnterCompilerDirective.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestErrorOnReadyTraceOutsideProcedureDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecCicsShowsErrorCorrectly.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestPseudoTextContentConstraint.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownBy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlIncludeStatementNotDefinedCorrectly.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTitleStatement.java
Labels: bug, enhancement
