Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-10, with the labels that each got.

#1134 test: Add more tests to CI
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F96125.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/package.json
Labels: pipeline, UI tests, hacktoberfest, hacktoberfest-accepted

#1137 test: add more wait time for encoding tests
  tests/cypress/integration/LSP/copybook.spec.js
Labels: bug, UI tests, hacktoberfest, hacktoberfest-accepted

#1138 test: fix Outline test
  tests/cypress/integration/LSP/F101836.spec.js
Labels: UI tests, hacktoberfest-accepted

#1139 test: fix TC247908 and TC247996
  tests/cypress/integration/LSP/F96117.spec.js
Labels: UI tests, hacktoberfest, hacktoberfest-accepted, hacktober-fest

#1140 test: add UseCase examples
  server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestMultiTokenError.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestParametrised.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestPositiveCase.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestReplacing.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithCopybook.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithErrorCheck.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithSubroutines.java
Labels: hacktoberfest

#1141 test: Update Cypress version to 8.5.0
  Jenkinsfile
  tests/package.json
  tests/yarn.lock
Labels: enhancement, UI tests, hacktoberfest, hacktoberfest-accepted

#1145 Update copyright pattern for internal contributions
  server/src/style/javaHeader.txt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1144 Create SECURITY.md
  SECURITY.md
Labels: documentation

#1142 feat: Support ++INCLUDE for copybooks #20
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIncludeStatement.java
Labels: new feature, hacktoberfest, hacktoberfest-accepted

#1147 Syntax fix in package.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: bug, hacktoberfest, hacktoberfest-accepted

#1146 Fix IDMS entity length error locations #704
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsBindStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsLoadStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsSections.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsStartpageStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsTransferStatement.java
Labels: bug, hacktoberfest, hacktoberfest-accepted

#1149 fix: Change the extension initialisation order #1040
  clients/cobol-lsp-vscode-extension/src/extension.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted

#1151 refactor: Create default config without logging an error
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
Labels: bug, hacktoberfest, hacktoberfest-accepted
