Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-02, with the labels that each got.

#756 Master
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/README.md
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: release

#758 fix : allow db2 sql keywords as cobol variable name
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/Db2SqlLexer.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSqlKeywordAllowedAsCobolVarIdentifier.java
Labels: bug

#754 feat: ui regression suite initial commit
  tests/.gitignore
  tests/README.md
  tests/cypress.json
  tests/cypress/.eslintrc.json
  tests/cypress/fixtures/example.json
  tests/cypress/integration/LSP/F101836.spec.js
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F95834.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F96125.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/index.ts
  tests/package.json
  tests/test_files/project/.copybooks/zowe-profile-1/DATA.SET.PATH1/BOOK1N.cpy
  tests/test_files/project/.copybooks/zowe-profile-1/DATA.SET.PATH1/BOOK2R.cpy
  tests/test_files/project/.copybooks/zowe-profile-1/DATA.SET.PATH2/BOOK1R.cpy
  tests/test_files/project/.copybooks/zowe-profile-1/DATA.SET.PATH2/BOOK2N.cpy
  tests/test_files/project/.copybooks/zowe-profile-1/DATA.SET.PATH2/BOOK3T.cpy
  tests/test_files/project/ADSORT.cbl
  tests/test_files/project/CALL.cbl
  tests/test_files/project/HELLO-WORLD.cbl
  tests/test_files/project/PAYLIB.CBL
  tests/test_files/project/REPLA.CBL
  tests/test_files/project/REPLACING.CBL
  tests/test_files/project/TEST.CBL
  tests/test_files/project/USER1.cbl
  tests/test_files/project/USER2.cbl
  tests/test_files/project/USERC1F.cbl
  tests/test_files/project/USERC1N1.cbl
  tests/test_files/project/USERC1N2.cbl
  tests/test_files/project/USERC1R.cbl
  tests/test_files/project/VAR.cbl
  tests/test_files/project/outline.cbl
  tests/test_files/project/subroutines/SUB1.cob
  tests/test_files/project/subroutines/SUB3.cobol
  tests/test_files/project/testing/A.cpy
  tests/test_files/project/testing/B
  tests/test_files/project/testing/NEW.CPY
  tests/test_files/project/testing/PAYLIB.CPY
  tests/test_files/project/testing/REPL
  tests/tsconfig.json
  tests/yarn.lock
Labels: enhancement

#759 feat: Add COPY IDMS support #704
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCopyIdms.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
Labels: new feature

#762 feat: add npm scripts + update README
  tests/README.md
  tests/package.json
Labels: UI tests

#764 Fix typos in the keywords documentation
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
Labels: documentation

#766 fix : allow db2 sql keywords as COBOL var identifier.
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/Db2SqlParser.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
Labels: bug

#767 fix : fix comment mismatch bewteen pre-processor and cobol-engine.
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
Labels: enhancement

#769 Master
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: release

#771 rewrite coloring support
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement

#773 feat: Support copybooks outside the current workspace #755
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/util/FSUtils.ts
Labels: new feature

#774 Upgrade Cypress to 6.4.0. Add mochawesome reporter. Add configs.
  tests/.gitignore
  tests/.huskyrc
  tests/.lintstagedrc
  tests/.prettierignore
  tests/.prettierrc
  tests/README.md
  tests/cypress.json
  tests/package.json
  tests/yarn.lock
Labels: UI tests

#775 feat: SKIP compiler directive can be terminated with a separator period.
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSkipStatement.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSkipStatementsAllowedEverywhere.java
Labels: new feature

#776 [UI_tests] Add @types/node
  tests/package.json
  tests/yarn.lock
Labels: UI tests

#779 build: Add husky config file to the root
  .huskyrc
Labels: UI tests

#778 feature: Collect and return ranges of paragraphs #777
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/GroupContext.java
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/SemanticContext.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/AnalysisResult.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/test/java/com/broadcom/lsp/cobol/core/semantics/GroupContextTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphRange.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSectionRange.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCaseEngine.java
Labels: new feature

#780 [UI_tests] Add TC318696 test case
  tests/README.md
  tests/cypress/integration/LSP/copybook.spec.js
  tests/test_files/test/BOOK3.cpy
  tests/test_files/test/files/BOOK3.cpy
Labels: UI tests
