Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-12, with the labels that each got.

#1201 Fix resolving SQLCA from workspace
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CopybookServiceTest.java
Labels: bug

#1197 feat: move copybook dependency to Zowe Explorer.
  Jenkinsfile
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/ChangeDefaultZoweProfileTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileUtilsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ZoweApiTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ZoweErrorTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/fetchCopybookCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/commands/ChangeDefaultZoweProfile.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/ProfileService.ts
  clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts
  clients/cobol-lsp-vscode-extension/src/services/ZoweError.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookURI.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybooksPathGenerator.ts
  clients/cobol-lsp-vscode-extension/src/services/util/ProfileUtils.ts
  clients/cobol-lsp-vscode-extension/tsconfig.json
Labels: new feature

#1203 Daco dml packet handling statement
  clients/cobol-lsp-vscode-extension/snippets.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/MessageServiceParser.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFOpenPacket.java
Labels: new feature

#1205 refactor: Create separate lexer for IDMS
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/IdmsLexer.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestAsteriskBeforeCopyDoesntBreakAnalysis.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestErrorOnReadyTraceOutsideProcedureDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNoNullPointerExpForIncompleteReplaceStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTitleStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTyposOnCompilerDirectives.java
Labels: enhancement

#1204 fix: Fix thread issue with error strategy for diff parsers.
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/ErrorMessageHelper.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
  server/src/main/java/org/eclipse/lsp/cobol/domain/modules/EngineModule.java
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/strategy/ErrorMessageHelperTest.java
Labels: bug

#1207 chore: Exclude unused checker dependency
  server/pom.xml
Labels: dependencies

#1206 feat: Support USS file download for copybooks.
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookURI.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybooksPathGenerator.ts
Labels: new feature

#1183 test: Add GitPod support. Part I.
  Jenkinsfile
  tests/cypress.json
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F95834.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/integration/LSP/zowe.spec.js
  tests/cypress/support/index.ts
  tests/package.json
  tests/tsconfig.json
  tests/yarn.lock
Labels: UI tests

#1213 ci: change theia image
  Jenkinsfile
Labels: pipeline, UI tests

#1215 Fix attempt to resolve predefined copybooks from the workspace
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
Labels: bug

#1216 fix: Make quoted string replacement work.
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/SearchPattern.java
  server/src/test/antlr4/org/eclipse/usecase/UseCasePreprocessor.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookReplacePatterns.java
Labels: bug

#1218 doc: Update README.md
  clients/cobol-lsp-vscode-extension/README.md
Labels: documentation

#1221 Readme updates for ZE dependency
  README.md
Labels: documentation

#1214 feat: Added DaCo DML Meta Information statements and Unit Tests #1126
  clients/cobol-lsp-vscode-extension/snippets.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/MessageServiceParser.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFGetEntityStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFGetItemStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFGetJobStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFGetNetworkStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFGetOdetteStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFGetTaskStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFGetUserStatement.java
Labels: new feature
