Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-06, with the labels that each got.

#932 test: workaround for cypress-tags and other small fixes
  tests/cypress.json
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/package.json
  tests/yarn.lock
Labels: UI tests

#929 fix: remove project dependency on AOP alliance.
  server/pom.xml
  server/src/main/java/org/eclipse/lsp/cobol/core/annotation/CheckServerShutdownState.java
  server/src/main/java/org/eclipse/lsp/cobol/core/annotation/CheckThreadInterruption.java
  server/src/main/java/org/eclipse/lsp/cobol/core/annotation/DisposableService.java
  server/src/main/java/org/eclipse/lsp/cobol/core/annotation/HandleShutdownState.java
  server/src/main/java/org/eclipse/lsp/cobol/core/annotation/HandleThreadInterruption.java
  server/src/main/java/org/eclipse/lsp/cobol/core/annotation/NonSyntheticMethodMatcher.java
  server/src/main/java/org/eclipse/lsp/cobol/core/annotation/ThreadInterruptAspect.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/ThreadInterruptionUtil.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/UserInterruptException.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/InterruptingTreeListener.java
  server/src/main/java/org/eclipse/lsp/cobol/domain/modules/ServiceModule.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolLSPServerStateService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/DisposableLSPStateService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/ShutdownCheckUtil.java
  server/src/test/java/org/eclipse/lsp/cobol/TestModule.java
  server/src/test/java/org/eclipse/lsp/cobol/core/annotation/HandleShutdownStateTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/annotation/HandleThreadInterruptionTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/annotation/NonSyntheticMethodMatcherTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/ThreadInterruptionUtilTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/ClientServerIntegrationTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/WorkspaceServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/TestLanguageServer.java
Labels: dependencies

#933 fix: any variable can contains redefines clause
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ConditionDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/GroupItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/IndexItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/MultiTableDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/RenameItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/StandAloneDataItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/TableDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableWithLevelNode.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineAsap.java
Labels: bug

#936 build: exclude some folders from vsix package
  clients/cobol-lsp-vscode-extension/.vscodeignore
  clients/cobol-lsp-vscode-extension/package.json
Labels: pipeline

#939 Fix issues found by static analysis
  server/src/main/java/org/eclipse/lsp/cobol/LangServerBootstrap.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
Labels: code smell

#940 Fix coverity issues with nodes
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/IfNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/Node.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ParagraphNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/PerformNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProcedureSectionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramEndNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramIdNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RootNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ConditionDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/GroupItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/IndexItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/MnemonicNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/MultiTableDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/RenameItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/StandAloneDataItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/TableDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableUsageNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableWithLevelNode.java
Labels: code smell

#937 add support for Datacom SQLDA and SQLCA implicit fields #885
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerFactory.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/ImplicitFields.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CFASTBuilderImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookConfig.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/SQLBackend.java
  server/src/main/java/org/eclipse/lsp/cobol/service/SettingsService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/references/ElementOccurrences.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/LanguageEngineFacade.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/FileSystemService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/SettingsParametersEnum.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java
  server/src/main/resources/implicitCopybooks/SQLCA_DATACOM.cpy
  server/src/main/resources/implicitCopybooks/SQLCA_DB2.cpy
  server/src/main/resources/implicitCopybooks/SQLDA.cpy
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/LangServerBootstrapTest.java
  server/src/test/java/org/eclipse/lsp/cobol/TestModule.java
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/impl/GrammarPreprocessorImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/ClientServerIntegrationTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CopybookServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/validations/UseCaseUtils.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockLanguageClient.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockLanguageServer.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlIncludeStatementForImplicitlyDefinedCpy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestUndefinedParentVariableUnderlined.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
  server/src/test/resources/implicitCopybooks/SQLCA_DATACOM.cpy
  server/src/test/resources/implicitCopybooks/SQLCA_DB2.cpy
  server/src/test/resources/implicitCopybooks/SQLDA.cpy
Labels: enhancement, new feature

#931 Update autocomplete list to add IDMS statements
  README.md
Labels: documentation

#941 Make socket streams closeable
  server/src/main/java/org/eclipse/lsp/cobol/LangServerBootstrap.java
  server/src/test/java/org/eclipse/lsp/cobol/LangServerBootstrapTest.java
Labels: code smell

#938 Create changelog for 0.19.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#935 Add sentence about CCF copybook support
  README.md
Labels: documentation

#943 Make socket communication closeable
  server/src/main/java/org/eclipse/lsp/cobol/LangServerBootstrap.java
Labels: code smell

#945 Refactor Index item hierarchy
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/IndexItemNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/MnemonicNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/MultiTableDataNameNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableWithLevelNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/AbstractVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/IndexItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MnemonicName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MultiTableDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/NodeConverter.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/StructuredVariable.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/IndexItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/MultiTableDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIndexItemMayBeGlobal.java
Labels: code smell

#950 Fix unread fields
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/CFASTNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/CFASTNodeType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/ElseIf.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/EndEvaluate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/EndIf.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/EndInlinePerform.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Evaluate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/GoTo.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/If.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/InlinePerform.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Paragraph.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Perform.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Program.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Section.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Stop.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/When.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CFASTBuilderImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/SettingsService.java
  server/src/test/java/org/eclipse/lsp/cobol/extendedapi/CFASTBuilderTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CopybookServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
  server/src/test/resources/cfast/case1.result.json
  server/src/test/resources/cfast/case3.result.json
  server/src/test/resources/cfast/case4.result.json
  server/src/test/resources/cfast/case5.result.json
  server/src/test/resources/cfast/case6.result.json
  server/src/test/resources/cfast/case_conditional_perform.result.json
  server/src/test/resources/cfast/case_evaluate.result.json
  server/src/test/resources/cfast/case_goto_keyword.result.json
  server/src/test/resources/cfast/case_ifs.result.json
  server/src/test/resources/cfast/case_ifs_1.result.json
  server/src/test/resources/cfast/case_ifs_2.result.json
Labels: code smell

#949 Fix dubious method usages
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/SQLBackend.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/FileSystemService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
Labels: code smell

#951 Fix race condition in test
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
Labels: enhancement

#958 fix: Fix an access to undefined element error in no workspace case #957
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
Labels: bug

#961 fix: Make analyse exceptions propagated to Extended Api responses. #960
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
Labels: bug

#967 Reduce resourse consumption
  Jenkinsfile
Labels: pipeline

#968 build: Bump commons-io
  server/pom.xml
Labels: dependencies

#962 Allow IDMS statements in conditional block #952
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyAfterIfNotProducesError.java
Labels: bug

#969 test: add TC326105 and fix other tests
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
  tests/cypress/support/index.ts
Labels: UI tests

#972 Bump google guava
  server/pom.xml
Labels: dependencies

#971 Fix hover for group items
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/AbstractVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/NodeConverter.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariablesHasChildren.java
Labels: bug

#959 Fix loading copybooks with any encoding
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java
Labels: bug

#975 Remove policy violating dependencies
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: dependencies

#980 fix: Clarify error message for invalid definition
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestAttachTaskCode.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestChangePriority.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookReplacePatterns.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestElementWithPICNotAllowedAsGroup.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestErrorsInDifferentFiles.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestGlobalVariables.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIncorrectTableCallUnderlined.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestMessageIfVariableNotDefined.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestProgramContexts.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestRenamesThruIncorrectOrder.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestRenamesWithNonExistingName.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestRenamingIncludesOnlyRequiredVariable.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplacingForSeveralTokensInOneLine.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSemanticErrorsFromCopybooksShownInDocument.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetOnOff.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownBy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlIncludeStatementForImplicitlyDefinedCpy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestUndefinedParentVariableUnderlined.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableInFileControl.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineSameGroup.java
Labels: bug, enhancement

#977 Fix incorrect IF statement parsing
  server/src/main/java/org/eclipse/lsp/cobol/service/CFASTBuilderImpl.java
Labels: bug

#984 feat: Add COPY MAID <name> support
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidStatement.java
Labels: new feature

#982 test: Adjust invalid definition error message
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
Labels: UI tests

#983 Create changelog for 0.19.1
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#991 After release 0.19.1
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: release

#987 feat: Add support for `COPY MAID <name>` statement
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidStatement.java
Labels: new feature

#992 feat: Add IDMS COPY support #704
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestErrorOnReadyTraceOutsideProcedureDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsCopy.java
Labels: new feature

#993 chore: update the coloring schema
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement
