Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-04, with the labels that each got.

#851 Make identifier pattern more effective
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/TechnicalLexer.g4
Labels: enhancement

#850 Update coloring with latest keywords
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement

#852 Add missing keywords to suggestion list
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
Labels: documentation

#853 Remove misspelled keyword
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlParser.g4
Labels: enhancement

#857 Fix syntax error on READY/RESET TRACE
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestErrorOnReadyTraceOutsideProcedureDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReadyAndResetTraceStatements.java
Labels: bug

#860 feat: Customize TAB button #841
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/SmartTabCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
Labels: new feature

#864 test: Add small enchantments
  tests/README.md
  tests/cypress/integration/LSP/lsp.spec.js
Labels: UI tests

#865 EXEC CICS block should be defined in Area B #858
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecCicsStatementMustCodedInAreaB.java
Labels: bug, enhancement

#862 feat: add Global variable support
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/Node.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/AbstractVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ElementItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/GroupItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/IndependentDataItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/IndexItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MnemonicName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MultiTableDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/RenameItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/StructuredVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/TableDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/Variable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/core/model/VariableUsageUtilsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/ElementItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/GroupItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/IndependentDataItemTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/MultiTableDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/TableDataNameTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestGlobalVariables.java
Labels: new feature

#869 Fix issues caused by latest CF AST changes
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/ElseIf.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/EndEvaluate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/EndIf.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/EndInlinePerform.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Evaluate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/GoTo.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/If.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/InlinePerform.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Paragraph.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Perform.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Program.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Section.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/Stop.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/When.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RootNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/StopNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
Labels: enhancement

#870 fix: exclude one char keywords from coloring
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: bug, enhancement

#873 fix: fix coloring for string literal in continuation line
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: bug

#871 feat: Add IDMS DML support for MAP statements part 1 #704
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsInquireMapStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapInStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapOutInStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapOutStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsStartpageStatement.java
Labels: new feature

#868 feat: Support REDEFINES clause #867
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecCicsSendStatementsArgumentsOrder.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineAsap.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineLevel.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineRedefined.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineValue.java
Labels: new feature

#874 feat: add new keywords to coloring rules
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: new feature

#872 test: Upgrade Cypress to 7.1.0
  tests/package.json
  tests/yarn.lock
Labels: UI tests

#878 refactor: add timers inside CobolLanguageEngine
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/Timing.java
Labels: enhancement

#877 refactor: wait for a language client to start on public api call
  clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
Labels: bug

#879 build : bump guava version in /server and y18n version in /clients/cobol-lsp-vscode-extension
  clients/cobol-lsp-vscode-extension/package-lock.json
  server/pom.xml
Labels: dependencies

#881 test: Update replacing suite
  tests/cypress/integration/LSP/F97476.spec.js
  tests/test_files/project/PAYLIB.CBL
  tests/test_files/project/REPLA.CBL
Labels: UI tests

#883 Introduce statements validation
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/messages/MessageService.java
  server/src/main/java/org/eclipse/lsp/cobol/core/messages/MessageTemplate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/messages/PropertiesMessageService.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/SyntaxError.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/NodeType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramEndNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetUpDownByStatement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/StatementNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/antlr4/org/eclipse/usecase/UseCasePreprocessor.g4
  server/src/test/java/org/eclipse/lsp/cobol/core/messages/PropertiesMessageServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownBy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownByInNestedProgram.java
  server/src/test/resources/resourceBundles/test_en.properties
Labels: new feature

#886 feature: support ENTER compiler directive.
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEnterCompilerDirective.java
Labels: new feature

#887 refactor: Unify dataName parser rule
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
Labels: enhancement

#888 Fix StackOverFlowException on tree nodes
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/AntlrVariableDefinitionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/EvaluateNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/EvaluateWhenNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ExitNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/GoBackNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/GoToNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/IfElseNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/IfNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/Node.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ParagraphNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/PerformNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProcedureDivisionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProcedureSectionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramEndNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramIdNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RootNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/SectionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/SentenceNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/StopNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/VariableDefinitionNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/VariableUsageNode.java
Labels: enhancement

#891 feat: Add support for IDMS DML commands #704
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCheckTerminal.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDelete.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsFreeStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsSetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsSnapStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsTransferStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsWaitStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsWriteClause.java
Labels: new feature

#890 Validate variables in SET TO TRUE/FALSE statement
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetToBooleanStatement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetToBoolean.java
Labels: new feature

#889 Validate variables in SET TO ON/OFF statement
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetToBooleanStatement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetToOnOffStatement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetUpDownByStatement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/StatementNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/AbstractVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ElementItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/GroupItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/IndependentDataItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/IndexItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MnemonicName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/MultiTableDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/RenameItem.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/StructureType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/StructuredVariable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/TableDataName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/Variable.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetOnOff.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetToBoolean.java
Labels: new feature

#893 Optimize CALL statement
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableUsageSeparatedByComma.java
Labels: enhancement

#894 feat: Add IDMS DML support for MAP statements part 2 #704
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapInStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsModifyMapStatement.java
Labels: new feature

#895 chore: Update coloring schema
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement

#896 ci: Increase maven memory
  Jenkinsfile
Labels: pipeline

#898 Optimize ambiguous parser rules
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
Labels: enhancement

#897 Fix order of message replacing patterns
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/resources/org/eclipse/lsp/cobol/core/strategy/SpecialTokenHandling.properties
Labels: enhancement

#901 Fix file system exception on initialize
  server/src/main/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategy.java
Labels: bug

#899 fix: replacement work if replacing or replaced text contains BY
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/ReplacingServiceImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/impl/ReplacingServiceImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookReplacePatterns.java
Labels: bug
