Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2021-01, with the labels that each got.

#712 Idms dml Add support for SCHEMA and MAP sections #704
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsSections.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
Labels: new feature

#713 Refactor the references support
  server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/ConstantLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/CopybookLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/ElementOccurrences.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/ParagraphLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SectionLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SemanticElementOccurrences.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SemanticLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SubroutineLocations.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/VariableLocations.java
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/AbstractReferenceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/ConstantLocationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/CopybookLocationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/ElementOccurrencesTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/ParagraphLocationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/SectionLocationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/SemanticElementOccurrencesTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/SubroutineLocationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/VariableLocationsTest.java
Labels: new feature

#716 style: Check javadocs and tests
  server/pom.xml
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/outline/OutlineNodeNames.java
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/outline/RangeUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/domain/event/factory/AnalysisFinishedSubscriberFactory.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/KeywordCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/ParagraphCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/SnippetCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/VariableCompletion.java
  server/src/style/checkstyle-suppressions.xml
  server/src/style/checkstyle.xml
  server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
  server/src/test/java/com/broadcom/lsp/cobol/core/annotation/HandleThreadInterruptionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/messages/LocaleStoreImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/messages/LogLevelUtilsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/messages/PropertiesMessageServiceTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/impl/CobolLineReaderImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/writer/impl/CobolLineWriterImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/semantics/CobolVariableContextTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/semantics/GroupContextTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/semantics/outline/RangeUtilsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusTestConstants.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/event/CopybookEventSubscribersTest.java
  server/src/test/java/com/broadcom/lsp/cobol/positive/FolderTextRegistry.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CobolDocumentModelTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/CopybookProcessingModeTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/SubroutineServiceImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/CompletionsChainTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/SectionCompletionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/SnippetCompletionTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/formations/FormationsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/ElementOccurrencesTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/NegativeUseCase.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/PositiveUseCase.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCopybookNameWithQuotes.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsControlSectionAll.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsSections.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestNoErrorOnCompilerDirectives.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestOutlineTreeLineNumbers.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphNotDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestPerformWithoutEndNotCauseNPE.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSectionDefined.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSqlIncludeStatementNotDefinedCorrectly.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestTitleStatement.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVariableUsageSeparatedByComma.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: code smell

#725 feat: supporting variable references in FILE-CONTROL
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVariableInFileControl.java
Labels: new feature

#731 refactor: add COMMENT as db-generic-name and null check
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/Db2SqlParser.g4
Labels: enhancement

#733 perf: Improve search variable by Qualificator
  server/src/main/java/com/broadcom/lsp/cobol/core/model/VariableUsageUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/AbstractVariable.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/ConditionDataName.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/ElementItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/GroupItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/IndependentDataItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/IndexItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/MnemonicName.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/MultiTableDataName.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/RenameItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/StructuredVariable.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/TableDataName.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/Variable.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/VariableUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/test/java/com/broadcom/lsp/cobol/core/model/VariableUsageUtilsTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/VariableUtilsTest.java
Labels: enhancement

#735 fix : Improve mapping mismatch caused due to SQL grammar
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessor.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CommonCobolLexer.g4
Labels: bug

#721 feat: Add support for 5 IDMS DML commands
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestAbendCode.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestAccept.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestAttachTaskCode.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestBind.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestChangePriority.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExtraneousInputEOFExpecting.java
Labels: new feature

#739 refactor: Fix SQL expressions
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/Db2SqlParser.g4
Labels: bug

#734 feat: Adjust Generated Error Messages #727
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/Db2SqlParser.g4
  server/src/main/java/com/broadcom/lsp/cobol/core/MessageServiceParser.java
  server/src/main/java/com/broadcom/lsp/cobol/core/strategy/CobolErrorStrategy.java
  server/src/main/resources/com/broadcom/lsp/cobol/core/strategy/SpecialTokenHandling.properties
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/com/broadcom/lsp/cobol/core/MessageServiceParserTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/com/broadcom/lsp/cobol/core/strategy/CobolErrorStrategyTest.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExtraneousInputEOFExpecting.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsControlSectionAll.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestRemarksAreUnsupported.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestRemarksSectionIsUnsupported.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSyntaxErrorOnCommunicationSection.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestUnexpectedCharErrorShown.java
Labels: enhancement, new feature

#736 Readme update for DB2 SQL
  README.md
Labels: documentation

#741 fix : Continuation Lines Not Concatenated with an Empty Line or comme…
  server/src/main/java/com/broadcom/lsp/cobol/core/model/CobolLine.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/CobolLineIndicatorProcessorImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/transformer/ContinuationLineTransformation.java
  server/src/test/java/com/broadcom/lsp/cobol/usecases/TestEmptyLinesAllowedBetweenContinuationLines.java
Labels: bug

#742 Check methods javadoc
  server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/VariableUsageUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderDelegate.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/CobolLineReWriter.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/transformer/CobolLinesTransformation.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/CobolLineUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/ReplacingServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/outline/OutlineTreeBuilder.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolDocumentModel.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/AnalysisResult.java
  server/src/main/java/com/broadcom/lsp/cobol/service/providers/ClientProvider.java
  server/src/style/checkstyle-suppressions.xml
  server/src/style/checkstyle.xml
  server/src/test/java/com/broadcom/lsp/cobol/negative/Chetest1Test.java
  server/src/test/java/com/broadcom/lsp/cobol/negative/Chetest2Test.java
  server/src/test/java/com/broadcom/lsp/cobol/negative/HelloDB2Test.java
  server/src/test/java/com/broadcom/lsp/cobol/negative/Marbles3Test.java
  server/src/test/java/com/broadcom/lsp/cobol/negative/MarblesTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/WatcherServiceImplTest.java
  server/src/test/java/com/broadcom/lsp/cobol/service/delegates/validations/UseCaseUtils.java
  server/src/test/java/com/broadcom/lsp/cobol/service/mocks/TestLanguageClient.java
  server/src/test/java/com/broadcom/lsp/cobol/service/mocks/TestLanguageServer.java
Labels: code smell, documentation

#743 test: Fix reliability issue in test
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusUnSubscribeTest.java
  server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusEventSubscriptionE2ETest.java
Labels: enhancement

#744 ci: Secure string interpolation in Jenkinsfile
  Jenkinsfile
Labels: pipeline

#745 build: Drop unused maven profile
  server/pom.xml
Labels: pipeline

#740 feat: make it run for Java 8
  clients/cobol-lsp-vscode-extension/src/__tests__/JavaCheckTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/JavaCheck.ts
  server/pom.xml
  server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/VariableUsageUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/ConditionDataName.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/MnemonicName.java
  server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/RenameItem.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CompilerDirectivesTransformation.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/CobolLineUtils.java
  server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/DocumentHierarchyLevel.java
  server/src/main/java/com/broadcom/lsp/cobol/core/semantics/outline/OutlineTreeBuilder.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableUsageDelegate.java
  server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/com/broadcom/lsp/cobol/service/SubroutineServiceImpl.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/ConstantCompletion.java
  server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/ElementOccurrences.java
  server/src/main/java/com/broadcom/lsp/cobol/service/utils/WorkspaceFileService.java
Labels: new feature

#748 test: Change parallelism for java tests
  server/pom.xml
Labels: pipeline

#749 Change Java version
  README.md
Labels: documentation

#747 style: Refactor Optional to fix reliability issue
  server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
Labels: code smell
