Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2022-03, with the labels that each got.

#1282 feat: Add DaCo DML FILE statements support #1126
  clients/cobol-lsp-vscode-extension/snippets.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFFileCloseStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFFileGetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFFileOpenStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFFileReadStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFFileWriteStatement.java
Labels: new feature

#1284 fix: Fix tab key for suggestions
  clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
Labels: bug

#1283 Provide support for WRK usage of COPY MAID
  server/src/main/java/org/eclipse/lsp/cobol/core/model/CopyStatementModifier.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/ProcessingConstants.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/CopybookModificationListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/LastVariableNameListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/DialectCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/CobolParserUtils.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWRK.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkDifferentCase.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkDoesNotTakeNameFrom88.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShortName.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorAfter77.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorAfterFiller.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorAfterVariableWithoutName.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorOnShortVariableName.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestPseudoTextContentConstraint.java
Labels: new feature

#1289 refactor: Clean COBOL ANTLR grammar
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/MessageServiceParser.java
  server/src/test/java/org/eclipse/lsp/cobol/core/MessageServiceParserTest.java
Labels: enhancement

#1294 fix: Use same variable name as VSCode
  clients/cobol-lsp-vscode-extension/src/__tests__/services/SettingsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
Labels: bug

#1292 Fix navigation for copybooks with qualifiers
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/AbstractCopybookAnalysis.java
  server/src/test/antlr4/org/eclipse/usecase/UseCasePreprocessor.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithKmkRequestsCorrectFile.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifier.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifierHasCorrectDefinition.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifierMissingCopybook.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/AnnotatedDocumentCleaning.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/TestData.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Labels: enhancement

#1297 refactor: Update coloring
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement

#1298 Do not process skipped copybooks
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/SkippingAnalysis.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidAllowsOnlyValidLevelNumbers.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidDoesNotShowMissingCopybookOnStatementWithoutNumber.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidIsNotResolvedInProcedureDivision.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSkippingCopybookAnalysis.java
Labels: enhancement

#1299 build: Update client dependencies
  clients/cobol-lsp-vscode-extension/package-lock.json
Labels: dependencies

#1293 doc: Provide changelog for version 1.0.0
  CHANGELOG.md
  clients/cobol-lsp-vscode-extension/CHANGELOG.md
Labels: documentation

#1302 refactor: hide maid copybook configurations
  clients/cobol-lsp-vscode-extension/package.json
Labels: enhancement

#1304 Upgrade client deps
  Jenkinsfile
  clients/cobol-lsp-vscode-extension/.vscodeignore
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
Labels: pipeline, dependencies

#1301 feat: Add DaCo String DML statements support #1126
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringAddStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringCheckStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringDeleteStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringFillStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringFindStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringGetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringInsertStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringMatchStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringNextStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFStringReplaceStatement.java
Labels: new feature

#1307 ci: Exclude old libraries from client
  clients/cobol-lsp-vscode-extension/.vscodeignore
Labels: pipeline, dependencies

#1312 test: Speed up typing tests
  server/src/test/java/org/eclipse/lsp/cobol/positive/TypingTest.java
Labels: enhancement, java

#1310 Fix resolving the analysis configuration
  server/src/main/java/org/eclipse/lsp/cobol/domain/modules/EngineModule.java
  server/src/main/java/org/eclipse/lsp/cobol/service/AnalysisConfig.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CachingConfigurationService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolWorkspaceServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/Configuration.java
  server/src/main/java/org/eclipse/lsp/cobol/service/ConfigurationImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/service/ConfigurationService.java
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CachingConfigurationServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/WorkspaceServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/IdmsBase.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/Test88ThruHover.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookNotProcessedInExtendedSource.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestFileDescriptor.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestMapDefinition.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestParagraphRange.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplaceCompilerDirective.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSectionRange.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSkipStatementsAllowedEverywhere.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlAnalysisDisabled.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlIncludeStatementForImplicitlyDefinedCpy.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableHasChildren.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCase.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
Labels: bug

#1313 (Doc) Update Readme
  README.md
  clients/cobol-lsp-vscode-extension/package.json
Labels: documentation
