Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2022-02, with the labels that each got.

#1252 feat: Add DaCo DML Table Row update statements support #1126
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowAddStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowDeleteStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowDuplicateStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowInsertStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowInvertStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowModifyStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowSingleStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableRowSortStatement.java
Labels: new feature

#1250 refactor: Decrease classes dependency
  clients/cobol-lsp-vscode-extension/sonar-project.properties
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/EditDatasetPathsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/commands/EditDatasetPathsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/commands/FetchCopybookCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/commands/OpenSettingsCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/commands/SmartTabCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/JavaCheckTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/LanguageClientServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/MiddlewareTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/SettingsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/CopybookResolveURITest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/CopybookURITest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/DownloadQueueTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/LocalCopybookResolverTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/reporter/TelemetryReporterImpl.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/reporter/TelemetryServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/util/DatasetUtilsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/util/ProfileUtilsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/util/SubroutineUtilsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/commands/EditDatasetPaths.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
  clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookURI.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybooksPathGenerator.ts
  clients/cobol-lsp-vscode-extension/src/services/util/DatasetUtils.ts
Labels: enhancement

#1246 refactor: change toggle comment line behavior
  clients/cobol-lsp-vscode-extension/src/__tests__/CommentCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/commands/CommentCommand.ts
Labels: bug

#1237 fix: Provide a setting to define encoding for USS files.
  Jenkinsfile
  clients/cobol-lsp-vscode-extension/package-lock.json
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/patches/iconv-lite+0.6.3.patch
  clients/cobol-lsp-vscode-extension/src/__tests__/EncodingIconvTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
Labels: bug

#1264 feat: Add DaCo DML File & String statements support #1126
  clients/cobol-lsp-vscode-extension/snippets.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
Labels: new feature

#1260 Add .cobol as a supported copybook extension
  README.md
  clients/cobol-lsp-vscode-extension/package.json
Labels: documentation

#1261 Adjust level numbers for COPY MAID and COPY IDMS
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/model/ResultWithErrors.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/CopybookHierarchy.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/LevelNumberAdjustingListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/DialectCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/RangeUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/TokenUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/RangeUtilsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/references/ElementOccurrencesTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestAdjustCopyMaidNumbers.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidAllowsOnlyValidLevelNumbers.java
Labels: new feature

#1265 chore: update syntax coloring
  clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Labels: enhancement

#1267 fix: make dot optional after END-IF
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfAndDot.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfDoesNotProduceError.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsBindStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsConDisconnectStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsDcStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsEraseStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsFindObtainStatements.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsGetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsKeepStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapInStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapOutStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsModifyMapStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsRollbackStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownBy.java
Labels: bug

#1269 fix: Process only program Node for CCF tree.
  server/src/main/java/org/eclipse/lsp/cobol/service/CFASTBuilderImpl.java
Labels: bug

#1268 refactor: Remove obsolete SemanticContext
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/SemanticContext.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
Labels: enhancement

#1274 Upgrade resources for pipeline and put some TCs to investigation
  Jenkinsfile
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/lsp.spec.js
Labels: pipeline, enhancement, UI tests

#1276 Update README.md
  README.md
Labels: documentation

#1273 Process COPY MAID qualifiers
  server/src/main/java/org/eclipse/lsp/cobol/core/model/CopyStatementModifier.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/CopybookHierarchy.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/CopybookModificationListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/AbstractCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CopybookName.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/DialectCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/PredefinedCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/positive/CobolText.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithKmkRequestsCorrectFile.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifier.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifierMissingCopybook.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestOutlineTree.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestOutlineTreeLineNumbers.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/AnnotatedDocumentCleaning.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/PredefinedCopybookUtils.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/TestData.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseUtils.java
Labels: new feature

#1277 refactor: Unify retrieval logic in UseCaseEngine
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableNode.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
Labels: enhancement

#1278 fix: Java Compile Error
  server/pom.xml
Labels: bug

#1281 build: Fix Java version variable in pom
  server/pom.xml
Labels: enhancement

#1280 feat: enhance the support for obsolete code
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/NodeType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RemarksNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/ObsoleteNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/resources/resourceBundles/messages_en.properties
  server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/statements/ObsoleteNodeTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestRemarksSectionIsUnsupported.java
Labels: new feature

#1279 feat: Add DaCo DML Table statements support #1126
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableGetStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFTableSortStatement.java
Labels: new feature
