Repository eclipse-che4z/che-che4z-lsp-for-cobol, pull requests merged in 2022-01, with the labels that each got.

#1222 refactor: add flavor ability
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/FlavorLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/FlavorParser.g4
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/Timing.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/flavors/CobolFlavor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/flavors/CobolFlavorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/flavors/EmptyFlavor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/flavors/FlavorOutcome.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/flavors/FlavorUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/flavors/TextReplacement.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/service/AnalysisConfig.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/SettingsParametersEnum.java
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestFlavorCase.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlAnalysisDisabled.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCase.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
Labels: enhancement

#1223 feat: Add DaCo DML Message handling statements support #1126
  clients/cobol-lsp-vscode-extension/snippets.json
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
  server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFReturnStatusStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFShowErrorMessageStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFShowMessageStatement.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDAFShowResultStatement.java
Labels: new feature

#1224 fix: allow redefining when data-name-1 and data-name-2 have the same …
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineLevel.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineSameGroup.java
Labels: bug

#1225 fix: Prompt proper error message for copybook download.
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybooksPathGenerator.ts
Labels: bug

#1227 feat: Evaluate variable in the path settings
  clients/cobol-lsp-vscode-extension/src/__tests__/SettingsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
  clients/cobol-lsp-vscode-extension/src/services/PathsService.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookURI.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybooksPathGenerator.ts
  clients/cobol-lsp-vscode-extension/src/services/util/ProfileUtils.ts
  clients/cobol-lsp-vscode-extension/src/services/util/SubroutineUtils.ts
Labels: new feature

#1228 Refactor copybooks processing
  server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/ExtendedDocument.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/ResultWithErrors.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/CopybookHierarchy.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerFactory.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/ReplacePreProcessorListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerFactory.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/PreprocessorStack.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/ReplacePreProcessorListener.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/ReplacePreprocessorFactory.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/ReplacingService.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/ReplacingServiceImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/AbstractCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CobolAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CopybookAnalysisFactory.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CopybookMetaData.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/DialectCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/PanvaletAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/PredefinedCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/PreprocessorFunctor.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/SkippingAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityFindingUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/TokenUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/NamedSubContext.java
  server/src/main/java/org/eclipse/lsp/cobol/core/semantics/SubContext.java
  server/src/main/java/org/eclipse/lsp/cobol/domain/modules/EngineModule.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
  server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/impl/GrammarPreprocessorImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityUtilsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/impl/ReplacingServiceImplTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidNotProcessedInExtendedSource.java
Labels: code smell, enhancement

#1233 Report missing copybook on COPY MAID
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/SkippingAnalysis.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSkippingCopybookAnalysis.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSkippingMissingCopybook.java
Labels: enhancement

#1232 test: Add changes to work on VSC
  tests/cypress/integration/LSP/F101836.spec.js
  tests/cypress/integration/LSP/F102470.spec.js
  tests/cypress/integration/LSP/F95833.spec.js
  tests/cypress/integration/LSP/F95834.spec.js
  tests/cypress/integration/LSP/F96117.spec.js
  tests/cypress/integration/LSP/F97476.spec.js
  tests/cypress/integration/LSP/copybook.spec.js
  tests/cypress/integration/LSP/zowe.spec.js
Labels: enhancement, UI tests

#1235 feat: Allow paths for different types of copybooks
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/MiddlewareTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/SettingsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookURI.ts
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/DialectType.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerImpl.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/AbstractCopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CopybookAnalysis.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CopybookMetaData.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookService.java
  server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
  server/src/test/java/org/eclipse/lsp/cobol/service/CopybookServiceTest.java
Labels: new feature

#1229 fix: Give option to download Zowe Explorer.
  clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/ProfileUtilsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/constants.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
  clients/cobol-lsp-vscode-extension/src/services/util/ProfileUtils.ts
Labels: bug

#1239 chore: Bump nanoid from 3.1.30 to 3.2.0
  clients/cobol-lsp-vscode-extension/package-lock.json
Labels: dependencies

#1238 refactor: Fix configuration properties for dialects
  README.md
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__tests__/SettingsTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/services/Settings.ts
  clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookURI.ts
Labels: enhancement

#1244 fix: Fix copybook definition lookup
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RootNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableNode.java
  server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/RangeUtils.java
  server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHover.java
  server/src/main/java/org/eclipse/lsp/cobol/service/delegates/references/ElementOccurrences.java
  server/src/main/java/org/eclipse/lsp/cobol/service/utils/SyntaxTreeUtil.java
  server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/CopyNodeRangeTest.java
  server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/RangeUtilsTest.java
  server/src/test/java/org/eclipse/lsp/cobol/service/delegates/references/ElementOccurrencesTest.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDefinitionOnLongCopybooks.java
  server/src/test/java/org/eclipse/lsp/cobol/usecases/TestFlavorCase.java
Labels: bug

#1240 feat: add comment line ability
  clients/cobol-lsp-vscode-extension/package.json
  clients/cobol-lsp-vscode-extension/src/__mocks__/vscode.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/CommentCommandTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
  clients/cobol-lsp-vscode-extension/src/commands/CommentCommand.ts
  clients/cobol-lsp-vscode-extension/src/extension.ts
Labels: new feature
